[0m21:35:30.989281 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7d931b04ee10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7d931b214550>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7d931b203a90>]}


============================== 21:35:30.992220 | 454239cf-115d-43d8-80f4-44bd3ef4ad29 ==============================
[0m21:35:30.992220 [info ] [MainThread]: Running with dbt=1.9.3
[0m21:35:30.992818 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/mnt/shares/dae-test-projects/DE-DBT-Google-Bigquery', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'debug': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'static_parser': 'True', 'invocation_command': 'dbt seed --select customers', 'introspect': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m21:35:30.993554 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /mnt/shares/dae-test-projects/DE-DBT-Google-Bigquery/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m21:35:30.996085 [debug] [MainThread]: Resource report: {"command_name": "seed", "command_success": false, "command_wall_clock_time": 0.049726013, "process_in_blocks": "112", "process_kernel_time": 0.164834, "process_mem_max_rss": "91028", "process_out_blocks": "0", "process_user_time": 1.066515}
[0m21:35:30.996575 [debug] [MainThread]: Command `dbt seed` failed at 21:35:30.996485 after 0.05 seconds
[0m21:35:30.997168 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7d931ebba110>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7d931b04f890>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7d931b04f3d0>]}
[0m21:35:30.997686 [debug] [MainThread]: Flushing usage events
[0m21:35:32.205793 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m21:38:09.880409 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x72e2b5ed5750>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x72e2b5f00c10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x72e2b5f01410>]}


============================== 21:38:09.883340 | f0e243f5-2397-4ab8-ad00-fba3ad9143f3 ==============================
[0m21:38:09.883340 [info ] [MainThread]: Running with dbt=1.9.3
[0m21:38:09.884071 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'profiles_dir': '/mnt/shares/dae-test-projects/DE-DBT-Google-Bigquery', 'log_path': '/mnt/shares/dae-test-projects/DE-DBT-Google-Bigquery/logs', 'version_check': 'True', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'invocation_command': 'dbt seed --select customers', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m21:38:09.886558 [error] [MainThread]: Encountered an error:
Runtime Error
  Could not find profile named 'bigquery_with_dbt'
[0m21:38:09.887546 [debug] [MainThread]: Resource report: {"command_name": "seed", "command_success": false, "command_wall_clock_time": 0.049358375, "process_in_blocks": "0", "process_kernel_time": 0.183432, "process_mem_max_rss": "91352", "process_out_blocks": "0", "process_user_time": 1.035223}
[0m21:38:09.888046 [debug] [MainThread]: Command `dbt seed` failed at 21:38:09.887954 after 0.05 seconds
[0m21:38:09.888546 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x72e2b5d57c10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x72e2ba35e190>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x72e2b5f023d0>]}
[0m21:38:09.889151 [debug] [MainThread]: Flushing usage events
[0m21:38:11.090050 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m21:38:48.555684 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7e3bfa109bd0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7e3bfa109450>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7e3bfa10b990>]}


============================== 21:38:48.558672 | 7495c7d8-b7bf-4a25-a753-65489802aa3d ==============================
[0m21:38:48.558672 [info ] [MainThread]: Running with dbt=1.9.3
[0m21:38:48.559344 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/mnt/shares/dae-test-projects/DE-DBT-Google-Bigquery', 'version_check': 'True', 'warn_error': 'None', 'log_path': '/mnt/shares/dae-test-projects/DE-DBT-Google-Bigquery/logs', 'debug': 'False', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'log_format': 'default', 'static_parser': 'True', 'target_path': 'None', 'invocation_command': 'dbt seed --select customers', 'send_anonymous_usage_stats': 'True'}
[0m21:38:48.561682 [error] [MainThread]: Encountered an error:
Runtime Error
  Could not find profile named 'DE-DBT-Google-Bigquery'
[0m21:38:48.562671 [debug] [MainThread]: Resource report: {"command_name": "seed", "command_success": false, "command_wall_clock_time": 0.050164495, "process_in_blocks": "0", "process_kernel_time": 0.180494, "process_mem_max_rss": "91456", "process_out_blocks": "0", "process_user_time": 1.061505}
[0m21:38:48.563194 [debug] [MainThread]: Command `dbt seed` failed at 21:38:48.563099 after 0.05 seconds
[0m21:38:48.563667 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7e3bfe59e190>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7e3bfa31c290>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7e3bf9f8bb90>]}
[0m21:38:48.564147 [debug] [MainThread]: Flushing usage events
[0m21:38:49.744002 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m21:39:46.958426 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7921e582db50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7921e5877610>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7921e64f9150>]}


============================== 21:39:46.961315 | 9c77051e-61e0-4e9b-8c32-9a53c1f0b09e ==============================
[0m21:39:46.961315 [info ] [MainThread]: Running with dbt=1.9.3
[0m21:39:46.962084 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'profiles_dir': '/mnt/shares/dae-test-projects/DE-DBT-Google-Bigquery', 'log_path': '/mnt/shares/dae-test-projects/DE-DBT-Google-Bigquery/logs', 'debug': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'log_format': 'default', 'invocation_command': 'dbt seed --select customers', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m21:39:47.728647 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'project_id', 'label': '9c77051e-61e0-4e9b-8c32-9a53c1f0b09e', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7921e5a33c90>]}
[0m21:39:47.777278 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'adapter_info', 'label': '9c77051e-61e0-4e9b-8c32-9a53c1f0b09e', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7921e7b39350>]}
[0m21:39:47.778128 [info ] [MainThread]: Registered adapter: bigquery=1.9.1
[0m21:39:48.340802 [debug] [MainThread]: checksum: 5671c00892cdbcef29c3b00cc5ba7510c3d18a35c883caeb9ab9ee266dc29c8f, vars: {}, profile: , target: , version: 1.9.3
[0m21:39:48.343635 [info ] [MainThread]: Unable to do partial parsing because saved manifest not found. Starting full parse.
[0m21:39:48.344766 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'partial_parser', 'label': '9c77051e-61e0-4e9b-8c32-9a53c1f0b09e', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7921c68aafd0>]}
[0m21:39:50.026566 [warn ] [MainThread]: [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
There are 1 unused configuration paths:
- models.bigquery_with_dbt.example
[0m21:39:50.030859 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'load_project', 'label': '9c77051e-61e0-4e9b-8c32-9a53c1f0b09e', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7921c66c0b50>]}
[0m21:39:50.075567 [debug] [MainThread]: Wrote artifact WritableManifest to /mnt/shares/dae-test-projects/DE-DBT-Google-Bigquery/target/manifest.json
[0m21:39:50.091540 [debug] [MainThread]: Wrote artifact SemanticManifest to /mnt/shares/dae-test-projects/DE-DBT-Google-Bigquery/target/semantic_manifest.json
[0m21:39:50.389288 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'resource_counts', 'label': '9c77051e-61e0-4e9b-8c32-9a53c1f0b09e', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7921c64641d0>]}
[0m21:39:50.392221 [info ] [MainThread]: Found 9 seeds, 491 macros
[0m21:39:50.395019 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'runnable_timing', 'label': '9c77051e-61e0-4e9b-8c32-9a53c1f0b09e', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7921c6509390>]}
[0m21:39:50.401375 [info ] [MainThread]: 
[0m21:39:50.404001 [info ] [MainThread]: Concurrency: 4 threads (target='dev')
[0m21:39:50.406405 [info ] [MainThread]: 
[0m21:39:50.409441 [debug] [MainThread]: Acquiring new bigquery connection 'master'
[0m21:39:50.413902 [debug] [ThreadPool]: Acquiring new bigquery connection 'list_gg-bigquery-datawarehouse'
[0m21:39:50.416425 [debug] [ThreadPool]: Opening a new connection, currently in state init
[0m21:39:50.419005 [debug] [ThreadPool]: BigQuery adapter: Got an error when attempting to create a bigquery " "client: '[Errno 2] No such file or directory: './keyfile.json''
[0m21:39:50.421951 [debug] [MainThread]: Opening a new connection, currently in state init
[0m21:39:50.424635 [debug] [MainThread]: BigQuery adapter: Got an error when attempting to create a bigquery " "client: '[Errno 2] No such file or directory: './keyfile.json''
[0m21:39:50.429487 [info ] [MainThread]: 
[0m21:39:50.432046 [info ] [MainThread]: Finished running  in 0 hours 0 minutes and 0.02 seconds (0.02s).
[0m21:39:50.434968 [error] [MainThread]: Encountered an error:
Database Error
  [Errno 2] No such file or directory: './keyfile.json'
[0m21:39:50.439593 [debug] [MainThread]: Resource report: {"command_name": "seed", "command_success": false, "command_wall_clock_time": 3.523324, "process_in_blocks": "96", "process_kernel_time": 0.448895, "process_mem_max_rss": "207864", "process_out_blocks": "0", "process_user_time": 3.293548}
[0m21:39:50.442847 [debug] [MainThread]: Command `dbt seed` failed at 21:39:50.442293 after 3.53 seconds
[0m21:39:50.445176 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7921e582d850>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7921c64a9f10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7921e582f8d0>]}
[0m21:39:50.447837 [debug] [MainThread]: Flushing usage events
[0m21:39:51.755405 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m21:40:08.778332 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x765be470d810>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x765be4763550>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x765be4911c10>]}


============================== 21:40:08.781300 | a83bdc3f-54d7-437d-9132-f54cd9687657 ==============================
[0m21:40:08.781300 [info ] [MainThread]: Running with dbt=1.9.3
[0m21:40:08.781974 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/mnt/shares/dae-test-projects/DE-DBT-Google-Bigquery', 'version_check': 'True', 'debug': 'False', 'log_path': '/mnt/shares/dae-test-projects/DE-DBT-Google-Bigquery/logs', 'warn_error': 'None', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt seed --select customers', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m21:40:09.545993 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'project_id', 'label': 'a83bdc3f-54d7-437d-9132-f54cd9687657', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x765be5553150>]}
[0m21:40:09.595232 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'adapter_info', 'label': 'a83bdc3f-54d7-437d-9132-f54cd9687657', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x765bd39c8f10>]}
[0m21:40:09.596022 [info ] [MainThread]: Registered adapter: bigquery=1.9.1
[0m21:40:09.877001 [debug] [MainThread]: checksum: 5671c00892cdbcef29c3b00cc5ba7510c3d18a35c883caeb9ab9ee266dc29c8f, vars: {}, profile: , target: , version: 1.9.3
[0m21:40:10.019048 [debug] [MainThread]: Partial parsing enabled: 0 files deleted, 0 files added, 0 files changed.
[0m21:40:10.019511 [debug] [MainThread]: Partial parsing enabled, no changes found, skipping parsing
[0m21:40:10.024637 [warn ] [MainThread]: [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
There are 1 unused configuration paths:
- models.bigquery_with_dbt.example
[0m21:40:10.038650 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'load_project', 'label': 'a83bdc3f-54d7-437d-9132-f54cd9687657', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x765be4588250>]}
[0m21:40:10.085193 [debug] [MainThread]: Wrote artifact WritableManifest to /mnt/shares/dae-test-projects/DE-DBT-Google-Bigquery/target/manifest.json
[0m21:40:10.088259 [debug] [MainThread]: Wrote artifact SemanticManifest to /mnt/shares/dae-test-projects/DE-DBT-Google-Bigquery/target/semantic_manifest.json
[0m21:40:10.102457 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'resource_counts', 'label': 'a83bdc3f-54d7-437d-9132-f54cd9687657', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x765bc970ff90>]}
[0m21:40:10.103105 [info ] [MainThread]: Found 9 seeds, 491 macros
[0m21:40:10.103599 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'runnable_timing', 'label': 'a83bdc3f-54d7-437d-9132-f54cd9687657', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x765bc9584d10>]}
[0m21:40:10.104933 [info ] [MainThread]: 
[0m21:40:10.105367 [info ] [MainThread]: Concurrency: 4 threads (target='dev')
[0m21:40:10.105780 [info ] [MainThread]: 
[0m21:40:10.106344 [debug] [MainThread]: Acquiring new bigquery connection 'master'
[0m21:40:10.107227 [debug] [ThreadPool]: Acquiring new bigquery connection 'list_gg-bigquery-datawarehouse'
[0m21:40:10.107669 [debug] [ThreadPool]: Opening a new connection, currently in state init
[0m21:40:10.108245 [info ] [ThreadPool]: BigQuery adapter: Please log into GCP to continue
[0m21:40:10.108643 [debug] [ThreadPool]: Executing "gcloud --version"
[0m21:40:10.109963 [debug] [ThreadPool]: BigQuery adapter: Got an error when attempting to create a bigquery " "client: 'Could not find command, ensure it is in the user's PATH: "gcloud"'
[0m21:40:10.110574 [debug] [MainThread]: Opening a new connection, currently in state init
[0m21:40:10.111194 [info ] [MainThread]: BigQuery adapter: Please log into GCP to continue
[0m21:40:10.111618 [debug] [MainThread]: Executing "gcloud --version"
[0m21:40:10.112792 [debug] [MainThread]: BigQuery adapter: Got an error when attempting to create a bigquery " "client: 'Could not find command, ensure it is in the user's PATH: "gcloud"'
[0m21:40:10.113490 [info ] [MainThread]: 
[0m21:40:10.113950 [info ] [MainThread]: Finished running  in 0 hours 0 minutes and 0.01 seconds (0.01s).
[0m21:40:10.115556 [error] [MainThread]: Encountered an error:
Database Error
  Could not find command, ensure it is in the user's PATH: "gcloud"
[0m21:40:10.116620 [debug] [MainThread]: Resource report: {"command_name": "seed", "command_success": false, "command_wall_clock_time": 1.3809329, "process_in_blocks": "0", "process_kernel_time": 0.354236, "process_mem_max_rss": "206328", "process_out_blocks": "0", "process_user_time": 2.411607}
[0m21:40:10.117091 [debug] [MainThread]: Command `dbt seed` failed at 21:40:10.117000 after 1.38 seconds
[0m21:40:10.117539 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x765be475d150>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x765be473a490>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x765bd1a54dd0>]}
[0m21:40:10.118064 [debug] [MainThread]: Flushing usage events
[0m21:40:11.325432 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m22:07:37.823463 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7a96cb146310>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7a96cb186250>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7a96cb146350>]}


============================== 22:07:37.826406 | 26c12b13-b27b-4422-9139-5606a66749ac ==============================
[0m22:07:37.826406 [info ] [MainThread]: Running with dbt=1.9.3
[0m22:07:37.827105 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/mnt/shares/dae-test-projects/DE-DBT-Google-Bigquery', 'debug': 'False', 'warn_error': 'None', 'log_path': '/mnt/shares/dae-test-projects/DE-DBT-Google-Bigquery/logs', 'version_check': 'True', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt seed --select customers', 'introspect': 'True', 'static_parser': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m22:07:38.603771 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'project_id', 'label': '26c12b13-b27b-4422-9139-5606a66749ac', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7a96b02dd110>]}
[0m22:07:38.652740 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'adapter_info', 'label': '26c12b13-b27b-4422-9139-5606a66749ac', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7a96cd4b8a90>]}
[0m22:07:38.653639 [info ] [MainThread]: Registered adapter: bigquery=1.9.1
[0m22:07:38.932900 [debug] [MainThread]: checksum: 5671c00892cdbcef29c3b00cc5ba7510c3d18a35c883caeb9ab9ee266dc29c8f, vars: {}, profile: , target: , version: 1.9.3
[0m22:07:39.074156 [debug] [MainThread]: Partial parsing enabled: 0 files deleted, 0 files added, 0 files changed.
[0m22:07:39.074614 [debug] [MainThread]: Partial parsing enabled, no changes found, skipping parsing
[0m22:07:39.079715 [warn ] [MainThread]: [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
There are 1 unused configuration paths:
- models.bigquery_with_dbt.example
[0m22:07:39.094743 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'load_project', 'label': '26c12b13-b27b-4422-9139-5606a66749ac', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7a96abfceb10>]}
[0m22:07:39.141395 [debug] [MainThread]: Wrote artifact WritableManifest to /mnt/shares/dae-test-projects/DE-DBT-Google-Bigquery/target/manifest.json
[0m22:07:39.144125 [debug] [MainThread]: Wrote artifact SemanticManifest to /mnt/shares/dae-test-projects/DE-DBT-Google-Bigquery/target/semantic_manifest.json
[0m22:07:39.158933 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'resource_counts', 'label': '26c12b13-b27b-4422-9139-5606a66749ac', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7a96abfcf890>]}
[0m22:07:39.159475 [info ] [MainThread]: Found 9 seeds, 491 macros
[0m22:07:39.160046 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'runnable_timing', 'label': '26c12b13-b27b-4422-9139-5606a66749ac', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7a96cc629d10>]}
[0m22:07:39.161365 [info ] [MainThread]: 
[0m22:07:39.161932 [info ] [MainThread]: Concurrency: 4 threads (target='dev')
[0m22:07:39.162292 [info ] [MainThread]: 
[0m22:07:39.163045 [debug] [MainThread]: Acquiring new bigquery connection 'master'
[0m22:07:39.163961 [debug] [ThreadPool]: Acquiring new bigquery connection 'list_gg-bigquery-datawarehouse'
[0m22:07:39.164541 [debug] [ThreadPool]: Opening a new connection, currently in state init
[0m22:07:39.165105 [info ] [ThreadPool]: BigQuery adapter: Please log into GCP to continue
[0m22:07:39.165495 [debug] [ThreadPool]: Executing "gcloud --version"
[0m22:07:39.870539 [debug] [ThreadPool]: STDOUT: "b'Google Cloud SDK 515.0.0\nalpha 2025.03.14\nbeta 2025.03.14\nbq 2.1.14\nbundled-python3-unix 3.12.8\ncore 2025.03.14\ngcloud-crc32c 1.0.0\ngsutil 5.33\n'"
[0m22:07:39.871363 [debug] [ThreadPool]: STDERR: "b''"
[0m22:07:39.871881 [debug] [ThreadPool]: Executing "gcloud auth application-default login"
[0m22:07:51.280402 [debug] [ThreadPool]: STDOUT: "b''"
[0m22:07:51.281347 [debug] [ThreadPool]: STDERR: "b'Your browser has been opened to visit:\n\n    https://accounts.google.com/o/oauth2/auth?response_type=code&client_id=764086051850-6qr4p6gpi6hn506pt8ejuq83di341hur.apps.googleusercontent.com&redirect_uri=http%3A%2F%2Flocalhost%3A8085%2F&scope=openid+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fsqlservice.login&state=4MPA9d5IOEENEpvtmaAl29AAlnUDOL&access_type=offline&code_challenge=PmqmkMYdrIqiVhlVTjLquTgZxRx4aIpGVqWAzMwUWNs&code_challenge_method=S256\n\n\nCredentials saved to file: [/home/zuongthao/.config/gcloud/application_default_credentials.json]\n\nThese credentials will be used by any library that requests Application Default Credentials (ADC).\n\nQuota project "gg-bigquery-datawarehouse" was added to ADC which can be used by Google client libraries for billing and quota. Note that some services may still bill the project owning the resource.\n'"
[0m22:07:51.282135 [debug] [ThreadPool]: BigQuery adapter: Got an error when attempting to create a bigquery " "client: 'Service account info was not in the expected format, missing fields client_email, token_uri.'
[0m22:07:51.282794 [debug] [MainThread]: Opening a new connection, currently in state init
[0m22:07:51.283469 [info ] [MainThread]: BigQuery adapter: Please log into GCP to continue
[0m22:07:51.283874 [debug] [MainThread]: Executing "gcloud --version"
[0m22:07:51.848225 [debug] [MainThread]: STDOUT: "b'Google Cloud SDK 515.0.0\nalpha 2025.03.14\nbeta 2025.03.14\nbq 2.1.14\nbundled-python3-unix 3.12.8\ncore 2025.03.14\ngcloud-crc32c 1.0.0\ngsutil 5.33\n'"
[0m22:07:51.848822 [debug] [MainThread]: STDERR: "b''"
[0m22:07:51.849214 [debug] [MainThread]: Executing "gcloud auth application-default login"
[0m22:08:02.868691 [debug] [MainThread]: STDOUT: "b''"
[0m22:08:02.869522 [debug] [MainThread]: STDERR: "b'Your browser has been opened to visit:\n\n    https://accounts.google.com/o/oauth2/auth?response_type=code&client_id=764086051850-6qr4p6gpi6hn506pt8ejuq83di341hur.apps.googleusercontent.com&redirect_uri=http%3A%2F%2Flocalhost%3A8085%2F&scope=openid+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fsqlservice.login&state=DC5LgTrtVP8FieBtstxglFG3qmdQSj&access_type=offline&code_challenge=KDvQW8eYWpXbTMCuXQnTth_tB26cN8gQEtH129vIVP4&code_challenge_method=S256\n\n\nCredentials saved to file: [/home/zuongthao/.config/gcloud/application_default_credentials.json]\n\nThese credentials will be used by any library that requests Application Default Credentials (ADC).\n\nQuota project "gg-bigquery-datawarehouse" was added to ADC which can be used by Google client libraries for billing and quota. Note that some services may still bill the project owning the resource.\n'"
[0m22:08:02.870313 [debug] [MainThread]: BigQuery adapter: Got an error when attempting to create a bigquery " "client: 'Service account info was not in the expected format, missing fields client_email, token_uri.'
[0m22:08:02.870768 [info ] [MainThread]: 
[0m22:08:02.871280 [info ] [MainThread]: Finished running  in 0 hours 0 minutes and 23.71 seconds (23.71s).
[0m22:08:02.872856 [error] [MainThread]: Encountered an error:
Database Error
  Service account info was not in the expected format, missing fields client_email, token_uri.
[0m22:08:02.873923 [debug] [MainThread]: Resource report: {"command_name": "seed", "command_success": false, "command_wall_clock_time": 25.092825, "process_in_blocks": "0", "process_kernel_time": 0.374556, "process_mem_max_rss": "206420", "process_out_blocks": "0", "process_user_time": 2.428703}
[0m22:08:02.874386 [debug] [MainThread]: Command `dbt seed` failed at 22:08:02.874298 after 25.09 seconds
[0m22:08:02.874837 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7a96cafc3cd0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7a96b0117a10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7a96cd497d10>]}
[0m22:08:02.875436 [debug] [MainThread]: Flushing usage events
[0m22:08:04.106387 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m22:21:07.483323 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7276a37879d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7276a3993e90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7276a37cb990>]}


============================== 22:21:07.486414 | d7de9d65-9043-4982-a3f7-f55547358fd6 ==============================
[0m22:21:07.486414 [info ] [MainThread]: Running with dbt=1.9.3
[0m22:21:07.487136 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/mnt/shares/dae-test-projects/DE-DBT-Google-Bigquery', 'fail_fast': 'False', 'debug': 'False', 'log_path': '/mnt/shares/dae-test-projects/DE-DBT-Google-Bigquery/logs', 'warn_error': 'None', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'invocation_command': 'dbt seed --select customers', 'introspect': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m22:21:08.254723 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'project_id', 'label': 'd7de9d65-9043-4982-a3f7-f55547358fd6', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x727688829290>]}
[0m22:21:08.303693 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'adapter_info', 'label': 'd7de9d65-9043-4982-a3f7-f55547358fd6', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7276a5af9450>]}
[0m22:21:08.304541 [info ] [MainThread]: Registered adapter: bigquery=1.9.1
[0m22:21:08.585850 [debug] [MainThread]: checksum: 5671c00892cdbcef29c3b00cc5ba7510c3d18a35c883caeb9ab9ee266dc29c8f, vars: {}, profile: , target: , version: 1.9.3
[0m22:21:08.683346 [info ] [MainThread]: Unable to do partial parsing because a project config has changed
[0m22:21:08.683873 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'partial_parser', 'label': 'd7de9d65-9043-4982-a3f7-f55547358fd6', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7276a4552190>]}
[0m22:21:09.501011 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'load_project', 'label': 'd7de9d65-9043-4982-a3f7-f55547358fd6', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7276886541d0>]}
[0m22:21:09.545143 [debug] [MainThread]: Wrote artifact WritableManifest to /mnt/shares/dae-test-projects/DE-DBT-Google-Bigquery/target/manifest.json
[0m22:21:09.547976 [debug] [MainThread]: Wrote artifact SemanticManifest to /mnt/shares/dae-test-projects/DE-DBT-Google-Bigquery/target/semantic_manifest.json
[0m22:21:09.561760 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'resource_counts', 'label': 'd7de9d65-9043-4982-a3f7-f55547358fd6', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7276882d5ed0>]}
[0m22:21:09.562280 [info ] [MainThread]: Found 9 seeds, 491 macros
[0m22:21:09.562731 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'runnable_timing', 'label': 'd7de9d65-9043-4982-a3f7-f55547358fd6', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x727688568e50>]}
[0m22:21:09.564038 [info ] [MainThread]: 
[0m22:21:09.564543 [info ] [MainThread]: Concurrency: 4 threads (target='dev')
[0m22:21:09.564973 [info ] [MainThread]: 
[0m22:21:09.565521 [debug] [MainThread]: Acquiring new bigquery connection 'master'
[0m22:21:09.566444 [debug] [ThreadPool]: Acquiring new bigquery connection 'list_gg-bigquery-datawarehouse'
[0m22:21:09.566993 [debug] [ThreadPool]: Opening a new connection, currently in state init
[0m22:21:10.402148 [debug] [ThreadPool]: Re-using an available connection from the pool (formerly list_gg-bigquery-datawarehouse, now create_gg-bigquery-datawarehouse_gg-bigquery-datawarehouse.BronzeLayer)
[0m22:21:10.405170 [debug] [ThreadPool]: Creating schema "database: "gg-bigquery-datawarehouse"
schema: "gg-bigquery-datawarehouse.BronzeLayer"
"
[0m22:21:10.438436 [debug] [ThreadPool]: On create_gg-bigquery-datawarehouse_gg-bigquery-datawarehouse.BronzeLayer: /* {"app": "dbt", "dbt_version": "1.9.3", "profile_name": "bigquery_with_dbt", "target_name": "dev", "connection_name": "create_gg-bigquery-datawarehouse_gg-bigquery-datawarehouse.BronzeLayer"} */
create schema if not exists `gg-bigquery-datawarehouse`.`gg-bigquery-datawarehouse.BronzeLayer`
  
[0m22:21:10.439739 [debug] [ThreadPool]: Opening a new connection, currently in state closed
[0m22:21:11.613553 [debug] [ThreadPool]: BigQuery adapter: https://console.cloud.google.com/bigquery?project=gg-bigquery-datawarehouse&j=bq:US:e0ce213f-6636-439e-9735-5ac586e82771&page=queryresults
[0m22:21:11.614847 [error] [ThreadPool]: BigQuery adapter: https://console.cloud.google.com/bigquery?project=gg-bigquery-datawarehouse&j=bq:US:e0ce213f-6636-439e-9735-5ac586e82771&page=queryresults
[0m22:21:11.615853 [debug] [ThreadPool]: BigQuery adapter: Unhandled error while running:
macro create_schema
[0m22:21:11.616592 [debug] [ThreadPool]: BigQuery adapter: Database Error
  Invalid project ID 'gg-bigquery-datawarehouse.gg-bigquery-datawarehouse'. Project IDs must contain 6-63 lowercase letters, digits, or dashes. Some project IDs also include domain name separated by a colon. IDs must start with a letter and may not end with a dash.
[0m22:21:11.618115 [debug] [MainThread]: Opening a new connection, currently in state init
[0m22:21:11.620625 [debug] [MainThread]: Connection 'master' was properly closed.
[0m22:21:11.621345 [debug] [MainThread]: Connection 'create_gg-bigquery-datawarehouse_gg-bigquery-datawarehouse.BronzeLayer' was properly closed.
[0m22:21:11.622117 [info ] [MainThread]: 
[0m22:21:11.622841 [info ] [MainThread]: Finished running  in 0 hours 0 minutes and 2.06 seconds (2.06s).
[0m22:21:11.623720 [error] [MainThread]: Encountered an error:
Database Error
  Invalid project ID 'gg-bigquery-datawarehouse.gg-bigquery-datawarehouse'. Project IDs must contain 6-63 lowercase letters, digits, or dashes. Some project IDs also include domain name separated by a colon. IDs must start with a letter and may not end with a dash.
[0m22:21:11.625000 [debug] [MainThread]: Resource report: {"command_name": "seed", "command_success": false, "command_wall_clock_time": 4.1847477, "process_in_blocks": "0", "process_kernel_time": 0.377783, "process_mem_max_rss": "208824", "process_out_blocks": "0", "process_user_time": 3.304103}
[0m22:21:11.625713 [debug] [MainThread]: Command `dbt seed` failed at 22:21:11.625579 after 4.19 seconds
[0m22:21:11.626414 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7276a3785810>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7276a7bbe390>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7276a39a0090>]}
[0m22:21:11.627018 [debug] [MainThread]: Flushing usage events
[0m22:21:12.850043 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m22:21:53.111258 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7ac40f4d7b50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7ac40f5c1e10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7ac40f5274d0>]}


============================== 22:21:53.114238 | ded5936e-1790-4049-9c76-2ad3781d5374 ==============================
[0m22:21:53.114238 [info ] [MainThread]: Running with dbt=1.9.3
[0m22:21:53.114881 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/mnt/shares/dae-test-projects/DE-DBT-Google-Bigquery', 'version_check': 'True', 'warn_error': 'None', 'log_path': '/mnt/shares/dae-test-projects/DE-DBT-Google-Bigquery/logs', 'fail_fast': 'False', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'log_format': 'default', 'invocation_command': 'dbt seed --select customers', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m22:21:53.883631 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'project_id', 'label': 'ded5936e-1790-4049-9c76-2ad3781d5374', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7ac40f4de190>]}
[0m22:21:53.932320 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'adapter_info', 'label': 'ded5936e-1790-4049-9c76-2ad3781d5374', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7ac411811510>]}
[0m22:21:53.933222 [info ] [MainThread]: Registered adapter: bigquery=1.9.1
[0m22:21:54.213255 [debug] [MainThread]: checksum: 5671c00892cdbcef29c3b00cc5ba7510c3d18a35c883caeb9ab9ee266dc29c8f, vars: {}, profile: , target: , version: 1.9.3
[0m22:21:54.310482 [info ] [MainThread]: Unable to do partial parsing because profile has changed
[0m22:21:54.311353 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'partial_parser', 'label': 'ded5936e-1790-4049-9c76-2ad3781d5374', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7ac40fbc0450>]}
[0m22:21:55.117971 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'load_project', 'label': 'ded5936e-1790-4049-9c76-2ad3781d5374', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7ac3f41a5c90>]}
[0m22:21:55.162439 [debug] [MainThread]: Wrote artifact WritableManifest to /mnt/shares/dae-test-projects/DE-DBT-Google-Bigquery/target/manifest.json
[0m22:21:55.165243 [debug] [MainThread]: Wrote artifact SemanticManifest to /mnt/shares/dae-test-projects/DE-DBT-Google-Bigquery/target/semantic_manifest.json
[0m22:21:55.179811 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'resource_counts', 'label': 'ded5936e-1790-4049-9c76-2ad3781d5374', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7ac3eff48990>]}
[0m22:21:55.180367 [info ] [MainThread]: Found 9 seeds, 491 macros
[0m22:21:55.180832 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'runnable_timing', 'label': 'ded5936e-1790-4049-9c76-2ad3781d5374', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7ac3f425a550>]}
[0m22:21:55.182139 [info ] [MainThread]: 
[0m22:21:55.182603 [info ] [MainThread]: Concurrency: 4 threads (target='dev')
[0m22:21:55.183085 [info ] [MainThread]: 
[0m22:21:55.183638 [debug] [MainThread]: Acquiring new bigquery connection 'master'
[0m22:21:55.184517 [debug] [ThreadPool]: Acquiring new bigquery connection 'list_gg-bigquery-datawarehouse'
[0m22:21:55.185060 [debug] [ThreadPool]: Opening a new connection, currently in state init
[0m22:21:55.906290 [debug] [ThreadPool]: Re-using an available connection from the pool (formerly list_gg-bigquery-datawarehouse, now list_gg-bigquery-datawarehouse_BronzeLayer)
[0m22:21:55.907070 [debug] [ThreadPool]: Opening a new connection, currently in state closed
[0m22:21:56.672884 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'runnable_timing', 'label': 'ded5936e-1790-4049-9c76-2ad3781d5374', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7ac3f4101110>]}
[0m22:21:56.676167 [debug] [MainThread]: Opening a new connection, currently in state init
[0m22:21:56.688078 [debug] [Thread-1 (]: Began running node seed.bigquery_with_dbt.customers
[0m22:21:56.688769 [info ] [Thread-1 (]: 1 of 1 START seed file BronzeLayer.customers ................................... [RUN]
[0m22:21:56.689379 [debug] [Thread-1 (]: Re-using an available connection from the pool (formerly list_gg-bigquery-datawarehouse_BronzeLayer, now seed.bigquery_with_dbt.customers)
[0m22:21:56.689866 [debug] [Thread-1 (]: Began compiling node seed.bigquery_with_dbt.customers
[0m22:21:56.690368 [debug] [Thread-1 (]: Began executing node seed.bigquery_with_dbt.customers
[0m22:21:57.921318 [debug] [Thread-1 (]: Opening a new connection, currently in state closed
[0m22:22:11.476561 [debug] [Thread-1 (]: On seed.bigquery_with_dbt.customers: /* {"app": "dbt", "dbt_version": "1.9.3", "profile_name": "bigquery_with_dbt", "target_name": "dev", "node_id": "seed.bigquery_with_dbt.customers"} */

    alter table `gg-bigquery-datawarehouse`.`BronzeLayer`.`customers` set OPTIONS()
  
[0m22:22:11.993942 [debug] [Thread-1 (]: BigQuery adapter: https://console.cloud.google.com/bigquery?project=gg-bigquery-datawarehouse&j=bq:US:dd238715-4be0-46a5-affb-fe2919b279e9&page=queryresults
[0m22:22:12.647971 [debug] [Thread-1 (]: Writing runtime SQL for node "seed.bigquery_with_dbt.customers"
[0m22:22:12.664857 [debug] [Thread-1 (]: Sending event: {'category': 'dbt', 'action': 'run_model', 'label': 'ded5936e-1790-4049-9c76-2ad3781d5374', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7ac3ee1d8d10>]}
[0m22:22:12.665440 [info ] [Thread-1 (]: 1 of 1 OK loaded seed file BronzeLayer.customers ............................... [[32mINSERT 99441[0m in 15.97s]
[0m22:22:12.666132 [debug] [Thread-1 (]: Finished running node seed.bigquery_with_dbt.customers
[0m22:22:12.667304 [debug] [MainThread]: Opening a new connection, currently in state closed
[0m22:22:12.668928 [debug] [MainThread]: Connection 'master' was properly closed.
[0m22:22:12.669355 [debug] [MainThread]: Connection 'seed.bigquery_with_dbt.customers' was properly closed.
[0m22:22:12.669772 [info ] [MainThread]: 
[0m22:22:12.670222 [info ] [MainThread]: Finished running 1 seed in 0 hours 0 minutes and 17.49 seconds (17.49s).
[0m22:22:12.670915 [debug] [MainThread]: Command end result
[0m22:22:12.699559 [debug] [MainThread]: Wrote artifact WritableManifest to /mnt/shares/dae-test-projects/DE-DBT-Google-Bigquery/target/manifest.json
[0m22:22:12.701049 [debug] [MainThread]: Wrote artifact SemanticManifest to /mnt/shares/dae-test-projects/DE-DBT-Google-Bigquery/target/semantic_manifest.json
[0m22:22:12.705766 [debug] [MainThread]: Wrote artifact RunExecutionResult to /mnt/shares/dae-test-projects/DE-DBT-Google-Bigquery/target/run_results.json
[0m22:22:12.706266 [info ] [MainThread]: 
[0m22:22:12.706758 [info ] [MainThread]: [32mCompleted successfully[0m
[0m22:22:12.707165 [info ] [MainThread]: 
[0m22:22:12.707549 [info ] [MainThread]: Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[0m22:22:12.708420 [debug] [MainThread]: Resource report: {"command_name": "seed", "command_success": true, "command_wall_clock_time": 19.639648, "process_in_blocks": "32", "process_kernel_time": 0.534136, "process_mem_max_rss": "328984", "process_out_blocks": "0", "process_user_time": 4.429721}
[0m22:22:12.708885 [debug] [MainThread]: Command `dbt seed` succeeded at 22:22:12.708796 after 19.64 seconds
[0m22:22:12.709326 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7ac41019d410>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7ac41395e390>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7ac41395e5d0>]}
[0m22:22:12.709767 [debug] [MainThread]: Flushing usage events
[0m22:22:13.910349 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m22:25:41.615180 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7a17f2fb3b50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7a17f2ffb550>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7a17f2fb20d0>]}


============================== 22:25:41.618092 | f59029b0-6ff8-40d7-ad85-a54c29bb133e ==============================
[0m22:25:41.618092 [info ] [MainThread]: Running with dbt=1.9.3
[0m22:25:41.618675 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'fail_fast': 'False', 'log_path': '/mnt/shares/dae-test-projects/DE-DBT-Google-Bigquery/logs', 'debug': 'False', 'profiles_dir': '/mnt/shares/dae-test-projects/DE-DBT-Google-Bigquery', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'introspect': 'True', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'invocation_command': 'dbt seed --select customers', 'send_anonymous_usage_stats': 'True'}
[0m22:25:42.387430 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'project_id', 'label': 'f59029b0-6ff8-40d7-ad85-a54c29bb133e', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7a17d9d20f10>]}
[0m22:25:42.436257 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'adapter_info', 'label': 'f59029b0-6ff8-40d7-ad85-a54c29bb133e', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7a17f52f8d10>]}
[0m22:25:42.437104 [info ] [MainThread]: Registered adapter: bigquery=1.9.1
[0m22:25:42.714549 [debug] [MainThread]: checksum: 5671c00892cdbcef29c3b00cc5ba7510c3d18a35c883caeb9ab9ee266dc29c8f, vars: {}, profile: , target: , version: 1.9.3
[0m22:25:42.854061 [debug] [MainThread]: Partial parsing enabled: 0 files deleted, 0 files added, 0 files changed.
[0m22:25:42.854516 [debug] [MainThread]: Partial parsing enabled, no changes found, skipping parsing
[0m22:25:42.871995 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'load_project', 'label': 'f59029b0-6ff8-40d7-ad85-a54c29bb133e', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7a17d3c9fa50>]}
[0m22:25:42.917196 [debug] [MainThread]: Wrote artifact WritableManifest to /mnt/shares/dae-test-projects/DE-DBT-Google-Bigquery/target/manifest.json
[0m22:25:42.919956 [debug] [MainThread]: Wrote artifact SemanticManifest to /mnt/shares/dae-test-projects/DE-DBT-Google-Bigquery/target/semantic_manifest.json
[0m22:25:42.932972 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'resource_counts', 'label': 'f59029b0-6ff8-40d7-ad85-a54c29bb133e', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7a17d3f472d0>]}
[0m22:25:42.933510 [info ] [MainThread]: Found 9 seeds, 491 macros
[0m22:25:42.934059 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'runnable_timing', 'label': 'f59029b0-6ff8-40d7-ad85-a54c29bb133e', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7a17d3db8210>]}
[0m22:25:42.935286 [info ] [MainThread]: 
[0m22:25:42.935740 [info ] [MainThread]: Concurrency: 4 threads (target='dev')
[0m22:25:42.936193 [info ] [MainThread]: 
[0m22:25:42.936756 [debug] [MainThread]: Acquiring new bigquery connection 'master'
[0m22:25:42.937756 [debug] [ThreadPool]: Acquiring new bigquery connection 'list_gg-bigquery-datawarehouse'
[0m22:25:42.938284 [debug] [ThreadPool]: Opening a new connection, currently in state init
[0m22:25:43.599789 [debug] [ThreadPool]: Re-using an available connection from the pool (formerly list_gg-bigquery-datawarehouse, now list_gg-bigquery-datawarehouse_BronzeLayer)
[0m22:25:43.602399 [debug] [ThreadPool]: Opening a new connection, currently in state closed
[0m22:25:44.243001 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'runnable_timing', 'label': 'f59029b0-6ff8-40d7-ad85-a54c29bb133e', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7a17ef933a10>]}
[0m22:25:44.244058 [debug] [MainThread]: Opening a new connection, currently in state init
[0m22:25:44.247944 [debug] [Thread-1 (]: Began running node seed.bigquery_with_dbt.customers
[0m22:25:44.248649 [info ] [Thread-1 (]: 1 of 1 START seed file BronzeLayer.customers ................................... [RUN]
[0m22:25:44.249315 [debug] [Thread-1 (]: Re-using an available connection from the pool (formerly list_gg-bigquery-datawarehouse_BronzeLayer, now seed.bigquery_with_dbt.customers)
[0m22:25:44.249759 [debug] [Thread-1 (]: Began compiling node seed.bigquery_with_dbt.customers
[0m22:25:44.250342 [debug] [Thread-1 (]: Began executing node seed.bigquery_with_dbt.customers
[0m22:25:45.161713 [debug] [Thread-1 (]: Opening a new connection, currently in state closed
[0m22:25:56.715314 [debug] [Thread-1 (]: On seed.bigquery_with_dbt.customers: /* {"app": "dbt", "dbt_version": "1.9.3", "profile_name": "bigquery_with_dbt", "target_name": "dev", "node_id": "seed.bigquery_with_dbt.customers"} */

    alter table `gg-bigquery-datawarehouse`.`BronzeLayer`.`customers` set OPTIONS()
  
[0m22:25:57.696534 [debug] [Thread-1 (]: BigQuery adapter: https://console.cloud.google.com/bigquery?project=gg-bigquery-datawarehouse&j=bq:US:a1f93bc9-2863-4bbb-a047-d85a3b87af3c&page=queryresults
[0m22:25:58.476213 [debug] [Thread-1 (]: Writing runtime SQL for node "seed.bigquery_with_dbt.customers"
[0m22:25:58.498520 [debug] [Thread-1 (]: Sending event: {'category': 'dbt', 'action': 'run_model', 'label': 'f59029b0-6ff8-40d7-ad85-a54c29bb133e', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7a17d1dfa690>]}
[0m22:25:58.499567 [info ] [Thread-1 (]: 1 of 1 OK loaded seed file BronzeLayer.customers ............................... [[32mINSERT 99441[0m in 14.25s]
[0m22:25:58.500755 [debug] [Thread-1 (]: Finished running node seed.bigquery_with_dbt.customers
[0m22:25:58.502626 [debug] [MainThread]: Opening a new connection, currently in state closed
[0m22:25:58.505294 [debug] [MainThread]: Connection 'master' was properly closed.
[0m22:25:58.506180 [debug] [MainThread]: Connection 'seed.bigquery_with_dbt.customers' was properly closed.
[0m22:25:58.507038 [info ] [MainThread]: 
[0m22:25:58.507774 [info ] [MainThread]: Finished running 1 seed in 0 hours 0 minutes and 15.57 seconds (15.57s).
[0m22:25:58.508928 [debug] [MainThread]: Command end result
[0m22:25:58.541388 [debug] [MainThread]: Wrote artifact WritableManifest to /mnt/shares/dae-test-projects/DE-DBT-Google-Bigquery/target/manifest.json
[0m22:25:58.543438 [debug] [MainThread]: Wrote artifact SemanticManifest to /mnt/shares/dae-test-projects/DE-DBT-Google-Bigquery/target/semantic_manifest.json
[0m22:25:58.548492 [debug] [MainThread]: Wrote artifact RunExecutionResult to /mnt/shares/dae-test-projects/DE-DBT-Google-Bigquery/target/run_results.json
[0m22:25:58.548974 [info ] [MainThread]: 
[0m22:25:58.549479 [info ] [MainThread]: [32mCompleted successfully[0m
[0m22:25:58.549860 [info ] [MainThread]: 
[0m22:25:58.550294 [info ] [MainThread]: Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[0m22:25:58.551171 [debug] [MainThread]: Resource report: {"command_name": "seed", "command_success": true, "command_wall_clock_time": 16.980276, "process_in_blocks": "0", "process_kernel_time": 0.48507, "process_mem_max_rss": "326720", "process_out_blocks": "0", "process_user_time": 3.605524}
[0m22:25:58.551627 [debug] [MainThread]: Command `dbt seed` succeeded at 22:25:58.551539 after 16.98 seconds
[0m22:25:58.552072 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7a17f31c4050>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7a17f3481590>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7a17f73b98d0>]}
[0m22:25:58.552489 [debug] [MainThread]: Flushing usage events
[0m22:25:59.748947 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m22:52:50.474294 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x77c8b0a25810>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x77c8b0a26610>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x77c8b0a27350>]}


============================== 22:52:50.477253 | cb5d881a-0b10-41f5-b915-4567115cfa25 ==============================
[0m22:52:50.477253 [info ] [MainThread]: Running with dbt=1.9.3
[0m22:52:50.477919 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'debug': 'False', 'log_path': '/mnt/shares/dae-test-projects/DE-DBT-Google-Bigquery/logs', 'fail_fast': 'False', 'profiles_dir': '/mnt/shares/dae-test-projects/DE-DBT-Google-Bigquery', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'static_parser': 'True', 'introspect': 'True', 'invocation_command': 'dbt seed', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m22:52:51.250420 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'project_id', 'label': 'cb5d881a-0b10-41f5-b915-4567115cfa25', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x77c895a0f190>]}
[0m22:52:51.299173 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'adapter_info', 'label': 'cb5d881a-0b10-41f5-b915-4567115cfa25', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x77c8b2d40dd0>]}
[0m22:52:51.300022 [info ] [MainThread]: Registered adapter: bigquery=1.9.1
[0m22:52:51.578624 [debug] [MainThread]: checksum: 5671c00892cdbcef29c3b00cc5ba7510c3d18a35c883caeb9ab9ee266dc29c8f, vars: {}, profile: , target: , version: 1.9.3
[0m22:52:51.719506 [debug] [MainThread]: Partial parsing enabled: 8 files deleted, 8 files added, 0 files changed.
[0m22:52:51.720123 [debug] [MainThread]: Partial parsing: added file: bigquery_with_dbt://seeds/order_payments.csv
[0m22:52:51.720608 [debug] [MainThread]: Partial parsing: added file: bigquery_with_dbt://seeds/catalog_name.csv
[0m22:52:51.721143 [debug] [MainThread]: Partial parsing: added file: bigquery_with_dbt://seeds/products.csv
[0m22:52:51.721603 [debug] [MainThread]: Partial parsing: added file: bigquery_with_dbt://seeds/geolocation.csv
[0m22:52:51.722140 [debug] [MainThread]: Partial parsing: added file: bigquery_with_dbt://seeds/orders.csv
[0m22:52:51.722584 [debug] [MainThread]: Partial parsing: added file: bigquery_with_dbt://seeds/order_items.csv
[0m22:52:51.723083 [debug] [MainThread]: Partial parsing: added file: bigquery_with_dbt://seeds/order_reviews.csv
[0m22:52:51.723458 [debug] [MainThread]: Partial parsing: added file: bigquery_with_dbt://seeds/sellers.csv
[0m22:52:51.723899 [debug] [MainThread]: Partial parsing: deleted file: bigquery_with_dbt://seeds/olist_order_payments_dataset.csv
[0m22:52:51.724268 [debug] [MainThread]: Partial parsing: deleted file: bigquery_with_dbt://seeds/olist_order_items_dataset.csv
[0m22:52:51.724689 [debug] [MainThread]: Partial parsing: deleted file: bigquery_with_dbt://seeds/olist_geolocation_dataset.csv
[0m22:52:51.725103 [debug] [MainThread]: Partial parsing: deleted file: bigquery_with_dbt://seeds/product_category_name_translation.csv
[0m22:52:51.725488 [debug] [MainThread]: Partial parsing: deleted file: bigquery_with_dbt://seeds/olist_sellers_dataset.csv
[0m22:52:51.726024 [debug] [MainThread]: Partial parsing: deleted file: bigquery_with_dbt://seeds/olist_products_dataset.csv
[0m22:52:51.726374 [debug] [MainThread]: Partial parsing: deleted file: bigquery_with_dbt://seeds/olist_order_reviews_dataset.csv
[0m22:52:51.726751 [debug] [MainThread]: Partial parsing: deleted file: bigquery_with_dbt://seeds/olist_orders_dataset.csv
[0m22:52:51.901621 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'load_project', 'label': 'cb5d881a-0b10-41f5-b915-4567115cfa25', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x77c8b0a34b90>]}
[0m22:52:51.943751 [debug] [MainThread]: Wrote artifact WritableManifest to /mnt/shares/dae-test-projects/DE-DBT-Google-Bigquery/target/manifest.json
[0m22:52:51.946477 [debug] [MainThread]: Wrote artifact SemanticManifest to /mnt/shares/dae-test-projects/DE-DBT-Google-Bigquery/target/semantic_manifest.json
[0m22:52:51.960800 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'resource_counts', 'label': 'cb5d881a-0b10-41f5-b915-4567115cfa25', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x77c8955215d0>]}
[0m22:52:51.961321 [info ] [MainThread]: Found 9 seeds, 491 macros
[0m22:52:51.961762 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'runnable_timing', 'label': 'cb5d881a-0b10-41f5-b915-4567115cfa25', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x77c895664950>]}
[0m22:52:51.963602 [info ] [MainThread]: 
[0m22:52:51.964158 [info ] [MainThread]: Concurrency: 4 threads (target='dev')
[0m22:52:51.964572 [info ] [MainThread]: 
[0m22:52:51.965207 [debug] [MainThread]: Acquiring new bigquery connection 'master'
[0m22:52:51.969563 [debug] [ThreadPool]: Acquiring new bigquery connection 'list_gg-bigquery-datawarehouse'
[0m22:52:51.970514 [debug] [ThreadPool]: Opening a new connection, currently in state init
[0m22:52:52.749326 [debug] [ThreadPool]: Re-using an available connection from the pool (formerly list_gg-bigquery-datawarehouse, now list_gg-bigquery-datawarehouse_BronzeLayer)
[0m22:52:52.752146 [debug] [ThreadPool]: Opening a new connection, currently in state closed
[0m22:52:53.426657 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'runnable_timing', 'label': 'cb5d881a-0b10-41f5-b915-4567115cfa25', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x77c895a458d0>]}
[0m22:52:53.429718 [debug] [MainThread]: Opening a new connection, currently in state init
[0m22:52:53.445104 [debug] [Thread-1 (]: Began running node seed.bigquery_with_dbt.catalog_name
[0m22:52:53.447025 [debug] [Thread-2 (]: Began running node seed.bigquery_with_dbt.customers
[0m22:52:53.448937 [debug] [Thread-3 (]: Began running node seed.bigquery_with_dbt.geolocation
[0m22:52:53.450932 [debug] [Thread-4 (]: Began running node seed.bigquery_with_dbt.order_items
[0m22:52:53.453603 [info ] [Thread-1 (]: 1 of 9 START seed file BronzeLayer.catalog_name ................................ [RUN]
[0m22:52:53.456808 [info ] [Thread-2 (]: 2 of 9 START seed file BronzeLayer.customers ................................... [RUN]
[0m22:52:53.459895 [info ] [Thread-3 (]: 3 of 9 START seed file BronzeLayer.geolocation ................................. [RUN]
[0m22:52:53.463048 [info ] [Thread-4 (]: 4 of 9 START seed file BronzeLayer.order_items ................................. [RUN]
[0m22:52:53.466224 [debug] [Thread-1 (]: Re-using an available connection from the pool (formerly list_gg-bigquery-datawarehouse_BronzeLayer, now seed.bigquery_with_dbt.catalog_name)
[0m22:52:53.467609 [debug] [Thread-2 (]: Acquiring new bigquery connection 'seed.bigquery_with_dbt.customers'
[0m22:52:53.468607 [debug] [Thread-3 (]: Acquiring new bigquery connection 'seed.bigquery_with_dbt.geolocation'
[0m22:52:53.469416 [debug] [Thread-4 (]: Acquiring new bigquery connection 'seed.bigquery_with_dbt.order_items'
[0m22:52:53.470123 [debug] [Thread-1 (]: Began compiling node seed.bigquery_with_dbt.catalog_name
[0m22:52:53.470668 [debug] [Thread-2 (]: Began compiling node seed.bigquery_with_dbt.customers
[0m22:52:53.471175 [debug] [Thread-3 (]: Began compiling node seed.bigquery_with_dbt.geolocation
[0m22:52:53.471668 [debug] [Thread-4 (]: Began compiling node seed.bigquery_with_dbt.order_items
[0m22:52:53.472193 [debug] [Thread-1 (]: Began executing node seed.bigquery_with_dbt.catalog_name
[0m22:52:53.472887 [debug] [Thread-2 (]: Began executing node seed.bigquery_with_dbt.customers
[0m22:52:53.473405 [debug] [Thread-3 (]: Began executing node seed.bigquery_with_dbt.geolocation
[0m22:52:53.473970 [debug] [Thread-4 (]: Began executing node seed.bigquery_with_dbt.order_items
[0m22:52:53.559677 [debug] [Thread-1 (]: Opening a new connection, currently in state closed
[0m22:52:56.136284 [debug] [Thread-2 (]: Opening a new connection, currently in state init
[0m22:53:00.023162 [debug] [Thread-1 (]: On seed.bigquery_with_dbt.catalog_name: /* {"app": "dbt", "dbt_version": "1.9.3", "profile_name": "bigquery_with_dbt", "target_name": "dev", "node_id": "seed.bigquery_with_dbt.catalog_name"} */

    alter table `gg-bigquery-datawarehouse`.`BronzeLayer`.`catalog_name` set OPTIONS()
  
[0m22:53:00.772605 [debug] [Thread-1 (]: BigQuery adapter: https://console.cloud.google.com/bigquery?project=gg-bigquery-datawarehouse&j=bq:US:8a6cf1cc-55ef-4087-9ac5-84a83751e301&page=queryresults
[0m22:53:02.447542 [debug] [Thread-1 (]: Writing runtime SQL for node "seed.bigquery_with_dbt.catalog_name"
[0m22:53:02.457866 [debug] [Thread-4 (]: Opening a new connection, currently in state init
[0m22:53:02.892357 [debug] [Thread-1 (]: Sending event: {'category': 'dbt', 'action': 'run_model', 'label': 'cb5d881a-0b10-41f5-b915-4567115cfa25', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x77c8803987d0>]}
[0m22:53:03.096473 [info ] [Thread-1 (]: 1 of 9 OK loaded seed file BronzeLayer.catalog_name ............................ [[32mINSERT 71[0m in 9.08s]
[0m22:53:03.118022 [debug] [Thread-1 (]: Finished running node seed.bigquery_with_dbt.catalog_name
[0m22:53:03.277196 [debug] [Thread-1 (]: Began running node seed.bigquery_with_dbt.order_payments
[0m22:53:03.293423 [info ] [Thread-1 (]: 5 of 9 START seed file BronzeLayer.order_payments .............................. [RUN]
[0m22:53:03.347453 [debug] [Thread-1 (]: Re-using an available connection from the pool (formerly seed.bigquery_with_dbt.catalog_name, now seed.bigquery_with_dbt.order_payments)
[0m22:53:03.368758 [debug] [Thread-1 (]: Began compiling node seed.bigquery_with_dbt.order_payments
[0m22:53:03.400478 [debug] [Thread-1 (]: Began executing node seed.bigquery_with_dbt.order_payments
[0m22:53:06.367844 [debug] [Thread-1 (]: Opening a new connection, currently in state closed
[0m22:53:11.220777 [debug] [Thread-2 (]: On seed.bigquery_with_dbt.customers: /* {"app": "dbt", "dbt_version": "1.9.3", "profile_name": "bigquery_with_dbt", "target_name": "dev", "node_id": "seed.bigquery_with_dbt.customers"} */

    alter table `gg-bigquery-datawarehouse`.`BronzeLayer`.`customers` set OPTIONS()
  
[0m22:53:12.179280 [debug] [Thread-2 (]: BigQuery adapter: https://console.cloud.google.com/bigquery?project=gg-bigquery-datawarehouse&j=bq:US:e5dfe580-7e98-4d51-8536-871d39bc48bf&page=queryresults
[0m22:53:13.601727 [debug] [Thread-2 (]: Writing runtime SQL for node "seed.bigquery_with_dbt.customers"
[0m22:53:13.661478 [debug] [Thread-2 (]: Sending event: {'category': 'dbt', 'action': 'run_model', 'label': 'cb5d881a-0b10-41f5-b915-4567115cfa25', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x77c86a9d73d0>]}
[0m22:53:13.682893 [info ] [Thread-2 (]: 2 of 9 OK loaded seed file BronzeLayer.customers ............................... [[32mINSERT 99441[0m in 20.19s]
[0m22:53:13.714776 [debug] [Thread-2 (]: Finished running node seed.bigquery_with_dbt.customers
[0m22:53:13.736090 [debug] [Thread-2 (]: Began running node seed.bigquery_with_dbt.order_reviews
[0m22:53:13.762432 [info ] [Thread-2 (]: 6 of 9 START seed file BronzeLayer.order_reviews ............................... [RUN]
[0m22:53:13.788833 [debug] [Thread-2 (]: Re-using an available connection from the pool (formerly seed.bigquery_with_dbt.customers, now seed.bigquery_with_dbt.order_reviews)
[0m22:53:13.809965 [debug] [Thread-2 (]: Began compiling node seed.bigquery_with_dbt.order_reviews
[0m22:53:13.831066 [debug] [Thread-2 (]: Began executing node seed.bigquery_with_dbt.order_reviews
[0m22:53:17.464580 [debug] [Thread-3 (]: Opening a new connection, currently in state init
[0m22:53:19.430306 [debug] [Thread-4 (]: On seed.bigquery_with_dbt.order_items: /* {"app": "dbt", "dbt_version": "1.9.3", "profile_name": "bigquery_with_dbt", "target_name": "dev", "node_id": "seed.bigquery_with_dbt.order_items"} */

    alter table `gg-bigquery-datawarehouse`.`BronzeLayer`.`order_items` set OPTIONS()
  
[0m22:53:19.431049 [debug] [Thread-1 (]: On seed.bigquery_with_dbt.order_payments: /* {"app": "dbt", "dbt_version": "1.9.3", "profile_name": "bigquery_with_dbt", "target_name": "dev", "node_id": "seed.bigquery_with_dbt.order_payments"} */

    alter table `gg-bigquery-datawarehouse`.`BronzeLayer`.`order_payments` set OPTIONS()
  
[0m22:53:19.991136 [debug] [Thread-4 (]: BigQuery adapter: https://console.cloud.google.com/bigquery?project=gg-bigquery-datawarehouse&j=bq:US:333f9a95-5d80-4b14-8844-370d6a3225fc&page=queryresults
[0m22:53:20.376439 [debug] [Thread-1 (]: BigQuery adapter: https://console.cloud.google.com/bigquery?project=gg-bigquery-datawarehouse&j=bq:US:b04715cd-14f4-4a75-aba5-c1a736d46616&page=queryresults
[0m22:53:20.817963 [debug] [Thread-4 (]: Writing runtime SQL for node "seed.bigquery_with_dbt.order_items"
[0m22:53:21.304332 [debug] [Thread-2 (]: Opening a new connection, currently in state closed
[0m22:53:21.364940 [debug] [Thread-4 (]: Sending event: {'category': 'dbt', 'action': 'run_model', 'label': 'cb5d881a-0b10-41f5-b915-4567115cfa25', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x77c86a9ea090>]}
[0m22:53:21.386130 [info ] [Thread-4 (]: 4 of 9 OK loaded seed file BronzeLayer.order_items ............................. [[32mINSERT 112650[0m in 27.90s]
[0m22:53:21.587723 [debug] [Thread-4 (]: Finished running node seed.bigquery_with_dbt.order_items
[0m22:53:21.608992 [debug] [Thread-4 (]: Began running node seed.bigquery_with_dbt.orders
[0m22:53:21.657497 [debug] [Thread-1 (]: Writing runtime SQL for node "seed.bigquery_with_dbt.order_payments"
[0m22:53:21.669626 [info ] [Thread-4 (]: 7 of 9 START seed file BronzeLayer.orders ...................................... [RUN]
[0m22:53:21.716942 [debug] [Thread-4 (]: Re-using an available connection from the pool (formerly seed.bigquery_with_dbt.order_items, now seed.bigquery_with_dbt.orders)
[0m22:53:21.739765 [debug] [Thread-4 (]: Began compiling node seed.bigquery_with_dbt.orders
[0m22:53:21.750613 [debug] [Thread-1 (]: Sending event: {'category': 'dbt', 'action': 'run_model', 'label': 'cb5d881a-0b10-41f5-b915-4567115cfa25', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x77c86a9f1b10>]}
[0m22:53:21.771110 [debug] [Thread-4 (]: Began executing node seed.bigquery_with_dbt.orders
[0m22:53:21.807689 [info ] [Thread-1 (]: 5 of 9 OK loaded seed file BronzeLayer.order_payments .......................... [[32mINSERT 103886[0m in 18.40s]
[0m22:53:21.885315 [debug] [Thread-1 (]: Finished running node seed.bigquery_with_dbt.order_payments
[0m22:53:21.980496 [debug] [Thread-1 (]: Began running node seed.bigquery_with_dbt.products
[0m22:53:22.395947 [info ] [Thread-1 (]: 8 of 9 START seed file BronzeLayer.products .................................... [RUN]
[0m22:53:22.486647 [debug] [Thread-1 (]: Re-using an available connection from the pool (formerly seed.bigquery_with_dbt.order_payments, now seed.bigquery_with_dbt.products)
[0m22:53:23.630815 [debug] [Thread-1 (]: Began compiling node seed.bigquery_with_dbt.products
[0m22:53:24.029437 [debug] [Thread-1 (]: Began executing node seed.bigquery_with_dbt.products
[0m22:53:28.101698 [debug] [Thread-1 (]: Opening a new connection, currently in state closed
[0m22:53:32.057086 [debug] [Thread-4 (]: Opening a new connection, currently in state closed
[0m22:53:37.072429 [error] [Thread-2 (]: [31mUnhandled error while executing [0m
400 Error while reading data, error message: CSV table encountered too many errors, giving up. Rows: 774; errors: 100. Please look into the errors[] collection for more details.; reason: invalid, message: Error while reading data, error message: CSV table encountered too many errors, giving up. Rows: 774; errors: 100. Please look into the errors[] collection for more details.; reason: invalid, message: Error while reading data, error message: CSV processing encountered too many errors, giving up. Rows: 774; errors: 100; max bad: 0; error percent: 0; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 5 columns.; line_number: 14 byte_offset_to_start_of_line: 1841 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 5 columns.; line_number: 30 byte_offset_to_start_of_line: 3855 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 5 columns.; line_number: 57 byte_offset_to_start_of_line: 7455 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 5 columns.; line_number: 68 byte_offset_to_start_of_line: 8729 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 5 columns.; line_number: 78 byte_offset_to_start_of_line: 10143 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 5 columns.; line_number: 110 byte_offset_to_start_of_line: 14219 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 5 columns.; line_number: 114 byte_offset_to_start_of_line: 14578 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 5 columns.; line_number: 128 byte_offset_to_start_of_line: 16216 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 5 columns.; line_number: 132 byte_offset_to_start_of_line: 16541 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 5 columns.; line_number: 138 byte_offset_to_start_of_line: 17245 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 5 columns.; line_number: 188 byte_offset_to_start_of_line: 23483 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 5 columns.; line_number: 192 byte_offset_to_start_of_line: 24203 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 5 columns.; line_number: 231 byte_offset_to_start_of_line: 29671 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 5 columns.; line_number: 261 byte_offset_to_start_of_line: 34016 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 5 columns.; line_number: 357 byte_offset_to_start_of_line: 48240 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 5 columns.; line_number: 359 byte_offset_to_start_of_line: 48387 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 5 columns.; line_number: 361 byte_offset_to_start_of_line: 48489 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 5 columns.; line_number: 374 byte_offset_to_start_of_line: 50339 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 5 columns.; line_number: 402 byte_offset_to_start_of_line: 54422 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 5 columns.; line_number: 430 byte_offset_to_start_of_line: 58426 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 5 columns.; line_number: 443 byte_offset_to_start_of_line: 60133 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 5 columns.; line_number: 455 byte_offset_to_start_of_line: 61986 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 5 columns.; line_number: 509 byte_offset_to_start_of_line: 69078 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 5 columns.; line_number: 520 byte_offset_to_start_of_line: 70482 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 5 columns.; line_number: 530 byte_offset_to_start_of_line: 71726 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 5 columns.; line_number: 532 byte_offset_to_start_of_line: 71993 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 5 columns.; line_number: 539 byte_offset_to_start_of_line: 72763 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 5 columns.; line_number: 547 byte_offset_to_start_of_line: 73595 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 5 columns.; line_number: 565 byte_offset_to_start_of_line: 75754 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 5 columns.; line_number: 568 byte_offset_to_start_of_line: 76042 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 5 columns.; line_number: 585 byte_offset_to_start_of_line: 78624 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 5 columns.; line_number: 590 byte_offset_to_start_of_line: 79305 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 5 columns.; line_number: 609 byte_offset_to_start_of_line: 81959 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 5 columns.; line_number: 624 byte_offset_to_start_of_line: 84231 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 5 columns.; line_number: 632 byte_offset_to_start_of_line: 84982 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 5 columns.; line_number: 698 byte_offset_to_start_of_line: 94475 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 5 columns.; line_number: 708 byte_offset_to_start_of_line: 96207 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 5 columns.; line_number: 771 byte_offset_to_start_of_line: 104882 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 5 columns.; line_number: 873 byte_offset_to_start_of_line: 119520 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 1 columns.; line_number: 15 byte_offset_to_start_of_line: 1960 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 1 columns.; line_number: 31 byte_offset_to_start_of_line: 3965 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 1 columns.; line_number: 69 byte_offset_to_start_of_line: 8875 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 1 columns.; line_number: 70 byte_offset_to_start_of_line: 8894 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 1 columns.; line_number: 79 byte_offset_to_start_of_line: 10286 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 1 columns.; line_number: 111 byte_offset_to_start_of_line: 14305 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 1 columns.; line_number: 115 byte_offset_to_start_of_line: 14715 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 1 columns.; line_number: 130 byte_offset_to_start_of_line: 16391 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 1 columns.; line_number: 139 byte_offset_to_start_of_line: 17388 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 1 columns.; line_number: 140 byte_offset_to_start_of_line: 17402 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 1 columns.; line_number: 141 byte_offset_to_start_of_line: 17403 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 1 columns.; line_number: 142 byte_offset_to_start_of_line: 17410 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 1 columns.; line_number: 232 byte_offset_to_start_of_line: 29816 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 1 columns.; line_number: 360 byte_offset_to_start_of_line: 48488 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 1 columns.; line_number: 444 byte_offset_to_start_of_line: 60273 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 1 columns.; line_number: 456 byte_offset_to_start_of_line: 62093 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 1 columns.; line_number: 457 byte_offset_to_start_of_line: 62121 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 1 columns.; line_number: 458 byte_offset_to_start_of_line: 62139 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 1 columns.; line_number: 521 byte_offset_to_start_of_line: 70596 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 1 columns.; line_number: 533 byte_offset_to_start_of_line: 72083 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 1 columns.; line_number: 548 byte_offset_to_start_of_line: 73708 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 1 columns.; line_number: 549 byte_offset_to_start_of_line: 73709 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 1 columns.; line_number: 550 byte_offset_to_start_of_line: 73714 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 1 columns.; line_number: 569 byte_offset_to_start_of_line: 76186 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 1 columns.; line_number: 591 byte_offset_to_start_of_line: 79416 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 1 columns.; line_number: 592 byte_offset_to_start_of_line: 79450 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 1 columns.; line_number: 610 byte_offset_to_start_of_line: 82085 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 1 columns.; line_number: 625 byte_offset_to_start_of_line: 84336 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 1 columns.; line_number: 626 byte_offset_to_start_of_line: 84356 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 1 columns.; line_number: 633 byte_offset_to_start_of_line: 85127 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 1 columns.; line_number: 709 byte_offset_to_start_of_line: 96343 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 1 columns.; line_number: 875 byte_offset_to_start_of_line: 119655 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 2 columns.; line_number: 32 byte_offset_to_start_of_line: 4016 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 2 columns.; line_number: 129 byte_offset_to_start_of_line: 16309 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 2 columns.; line_number: 540 byte_offset_to_start_of_line: 72871 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 2 columns.; line_number: 772 byte_offset_to_start_of_line: 105046 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 2 columns.; line_number: 874 byte_offset_to_start_of_line: 119609 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 3 columns.; line_number: 33 byte_offset_to_start_of_line: 4071 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 3 columns.; line_number: 58 byte_offset_to_start_of_line: 7576 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 3 columns.; line_number: 116 byte_offset_to_start_of_line: 14716 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 3 columns.; line_number: 133 byte_offset_to_start_of_line: 16638 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 3 columns.; line_number: 143 byte_offset_to_start_of_line: 17411 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 3 columns.; line_number: 189 byte_offset_to_start_of_line: 23712 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 3 columns.; line_number: 193 byte_offset_to_start_of_line: 24340 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 3 columns.; line_number: 358 byte_offset_to_start_of_line: 48328 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 3 columns.; line_number: 375 byte_offset_to_start_of_line: 50574 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 3 columns.; line_number: 403 byte_offset_to_start_of_line: 54535 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 3 columns.; line_number: 431 byte_offset_to_start_of_line: 58524 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 3 columns.; line_number: 510 byte_offset_to_start_of_line: 69203 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 3 columns.; line_number: 531 byte_offset_to_start_of_line: 71936 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 3 columns.; line_number: 541 byte_offset_to_start_of_line: 72932 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 3 columns.; line_number: 566 byte_offset_to_start_of_line: 75863 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 3 columns.; line_number: 593 byte_offset_to_start_of_line: 79494 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 3 columns.; line_number: 611 byte_offset_to_start_of_line: 82106 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 3 columns.; line_number: 699 byte_offset_to_start_of_line: 94606 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 3 columns.; line_number: 710 byte_offset_to_start_of_line: 96369 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 4 columns.; line_number: 131 byte_offset_to_start_of_line: 16421 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 4 columns.; line_number: 262 byte_offset_to_start_of_line: 34212 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 4 columns.; line_number: 586 byte_offset_to_start_of_line: 78746 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 4 columns.; line_number: 627 byte_offset_to_start_of_line: 84376 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 4 columns.; line_number: 773 byte_offset_to_start_of_line: 105081 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: You are loading data without specifying data format, data will be treated as CSV format by default. If this is not what you mean, please specify data format by --source_format.
[0m22:53:37.235731 [debug] [Thread-2 (]: Traceback (most recent call last):
  File "/mnt/shares/dae-test-projects/.venv/lib/python3.11/site-packages/dbt/task/base.py", line 361, in safe_run
    result = self.compile_and_execute(manifest, ctx)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/shares/dae-test-projects/.venv/lib/python3.11/site-packages/dbt/task/base.py", line 308, in compile_and_execute
    result = self.run(ctx.node, manifest)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/shares/dae-test-projects/.venv/lib/python3.11/site-packages/dbt/task/base.py", line 408, in run
    return self.execute(compiled_node, manifest)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/shares/dae-test-projects/.venv/lib/python3.11/site-packages/dbt/task/run.py", line 334, in execute
    return self._execute_model(hook_ctx, context_config, model, context, materialization_macro)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/shares/dae-test-projects/.venv/lib/python3.11/site-packages/dbt/task/run.py", line 294, in _execute_model
    result = MacroGenerator(
             ^^^^^^^^^^^^^^^
  File "/mnt/shares/dae-test-projects/.venv/lib/python3.11/site-packages/dbt/clients/jinja.py", line 82, in __call__
    return self.call_macro(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/shares/dae-test-projects/.venv/lib/python3.11/site-packages/dbt_common/clients/jinja.py", line 389, in call_macro
    return macro(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/shares/dae-test-projects/.venv/lib/python3.11/site-packages/jinja2/runtime.py", line 770, in __call__
    return self._invoke(arguments, autoescape)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/shares/dae-test-projects/.venv/lib/python3.11/site-packages/jinja2/runtime.py", line 784, in _invoke
    rv = self._func(*arguments)
         ^^^^^^^^^^^^^^^^^^^^^^
  File "<template>", line 109, in macro
  File "/mnt/shares/dae-test-projects/.venv/lib/python3.11/site-packages/jinja2/sandbox.py", line 401, in call
    return __context.call(__obj, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/shares/dae-test-projects/.venv/lib/python3.11/site-packages/jinja2/runtime.py", line 303, in call
    return __obj(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/shares/dae-test-projects/.venv/lib/python3.11/site-packages/dbt/clients/jinja.py", line 82, in __call__
    return self.call_macro(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/shares/dae-test-projects/.venv/lib/python3.11/site-packages/dbt_common/clients/jinja.py", line 389, in call_macro
    return macro(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/shares/dae-test-projects/.venv/lib/python3.11/site-packages/jinja2/runtime.py", line 770, in __call__
    return self._invoke(arguments, autoescape)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/shares/dae-test-projects/.venv/lib/python3.11/site-packages/jinja2/runtime.py", line 784, in _invoke
    rv = self._func(*arguments)
         ^^^^^^^^^^^^^^^^^^^^^^
  File "<template>", line 21, in macro
  File "/mnt/shares/dae-test-projects/.venv/lib/python3.11/site-packages/jinja2/sandbox.py", line 401, in call
    return __context.call(__obj, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/shares/dae-test-projects/.venv/lib/python3.11/site-packages/jinja2/runtime.py", line 303, in call
    return __obj(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/shares/dae-test-projects/.venv/lib/python3.11/site-packages/dbt/clients/jinja.py", line 82, in __call__
    return self.call_macro(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/shares/dae-test-projects/.venv/lib/python3.11/site-packages/dbt_common/clients/jinja.py", line 389, in call_macro
    return macro(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/shares/dae-test-projects/.venv/lib/python3.11/site-packages/jinja2/runtime.py", line 770, in __call__
    return self._invoke(arguments, autoescape)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/shares/dae-test-projects/.venv/lib/python3.11/site-packages/jinja2/runtime.py", line 784, in _invoke
    rv = self._func(*arguments)
         ^^^^^^^^^^^^^^^^^^^^^^
  File "<template>", line 25, in macro
  File "/mnt/shares/dae-test-projects/.venv/lib/python3.11/site-packages/jinja2/sandbox.py", line 401, in call
    return __context.call(__obj, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/shares/dae-test-projects/.venv/lib/python3.11/site-packages/jinja2/runtime.py", line 303, in call
    return __obj(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/shares/dae-test-projects/.venv/lib/python3.11/site-packages/dbt/adapters/bigquery/impl.py", line 666, in load_dataframe
    self.connections.write_dataframe_to_table(
  File "/mnt/shares/dae-test-projects/.venv/lib/python3.11/site-packages/dbt/adapters/bigquery/connections.py", line 465, in write_dataframe_to_table
    self._write_file_to_table(client, file_path, table, load_config, fallback_timeout)
  File "/mnt/shares/dae-test-projects/.venv/lib/python3.11/site-packages/dbt/adapters/bigquery/connections.py", line 497, in _write_file_to_table
    response = job.result(retry=self._retry.create_retry(fallback=fallback_timeout))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/shares/dae-test-projects/.venv/lib/python3.11/site-packages/google/cloud/bigquery/job/base.py", line 969, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/shares/dae-test-projects/.venv/lib/python3.11/site-packages/google/api_core/future/polling.py", line 261, in result
    raise self._exception
google.api_core.exceptions.BadRequest: 400 Error while reading data, error message: CSV table encountered too many errors, giving up. Rows: 774; errors: 100. Please look into the errors[] collection for more details.; reason: invalid, message: Error while reading data, error message: CSV table encountered too many errors, giving up. Rows: 774; errors: 100. Please look into the errors[] collection for more details.; reason: invalid, message: Error while reading data, error message: CSV processing encountered too many errors, giving up. Rows: 774; errors: 100; max bad: 0; error percent: 0; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 5 columns.; line_number: 14 byte_offset_to_start_of_line: 1841 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 5 columns.; line_number: 30 byte_offset_to_start_of_line: 3855 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 5 columns.; line_number: 57 byte_offset_to_start_of_line: 7455 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 5 columns.; line_number: 68 byte_offset_to_start_of_line: 8729 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 5 columns.; line_number: 78 byte_offset_to_start_of_line: 10143 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 5 columns.; line_number: 110 byte_offset_to_start_of_line: 14219 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 5 columns.; line_number: 114 byte_offset_to_start_of_line: 14578 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 5 columns.; line_number: 128 byte_offset_to_start_of_line: 16216 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 5 columns.; line_number: 132 byte_offset_to_start_of_line: 16541 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 5 columns.; line_number: 138 byte_offset_to_start_of_line: 17245 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 5 columns.; line_number: 188 byte_offset_to_start_of_line: 23483 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 5 columns.; line_number: 192 byte_offset_to_start_of_line: 24203 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 5 columns.; line_number: 231 byte_offset_to_start_of_line: 29671 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 5 columns.; line_number: 261 byte_offset_to_start_of_line: 34016 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 5 columns.; line_number: 357 byte_offset_to_start_of_line: 48240 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 5 columns.; line_number: 359 byte_offset_to_start_of_line: 48387 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 5 columns.; line_number: 361 byte_offset_to_start_of_line: 48489 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 5 columns.; line_number: 374 byte_offset_to_start_of_line: 50339 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 5 columns.; line_number: 402 byte_offset_to_start_of_line: 54422 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 5 columns.; line_number: 430 byte_offset_to_start_of_line: 58426 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 5 columns.; line_number: 443 byte_offset_to_start_of_line: 60133 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 5 columns.; line_number: 455 byte_offset_to_start_of_line: 61986 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 5 columns.; line_number: 509 byte_offset_to_start_of_line: 69078 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 5 columns.; line_number: 520 byte_offset_to_start_of_line: 70482 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 5 columns.; line_number: 530 byte_offset_to_start_of_line: 71726 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 5 columns.; line_number: 532 byte_offset_to_start_of_line: 71993 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 5 columns.; line_number: 539 byte_offset_to_start_of_line: 72763 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 5 columns.; line_number: 547 byte_offset_to_start_of_line: 73595 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 5 columns.; line_number: 565 byte_offset_to_start_of_line: 75754 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 5 columns.; line_number: 568 byte_offset_to_start_of_line: 76042 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 5 columns.; line_number: 585 byte_offset_to_start_of_line: 78624 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 5 columns.; line_number: 590 byte_offset_to_start_of_line: 79305 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 5 columns.; line_number: 609 byte_offset_to_start_of_line: 81959 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 5 columns.; line_number: 624 byte_offset_to_start_of_line: 84231 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 5 columns.; line_number: 632 byte_offset_to_start_of_line: 84982 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 5 columns.; line_number: 698 byte_offset_to_start_of_line: 94475 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 5 columns.; line_number: 708 byte_offset_to_start_of_line: 96207 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 5 columns.; line_number: 771 byte_offset_to_start_of_line: 104882 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 5 columns.; line_number: 873 byte_offset_to_start_of_line: 119520 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 1 columns.; line_number: 15 byte_offset_to_start_of_line: 1960 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 1 columns.; line_number: 31 byte_offset_to_start_of_line: 3965 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 1 columns.; line_number: 69 byte_offset_to_start_of_line: 8875 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 1 columns.; line_number: 70 byte_offset_to_start_of_line: 8894 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 1 columns.; line_number: 79 byte_offset_to_start_of_line: 10286 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 1 columns.; line_number: 111 byte_offset_to_start_of_line: 14305 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 1 columns.; line_number: 115 byte_offset_to_start_of_line: 14715 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 1 columns.; line_number: 130 byte_offset_to_start_of_line: 16391 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 1 columns.; line_number: 139 byte_offset_to_start_of_line: 17388 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 1 columns.; line_number: 140 byte_offset_to_start_of_line: 17402 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 1 columns.; line_number: 141 byte_offset_to_start_of_line: 17403 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 1 columns.; line_number: 142 byte_offset_to_start_of_line: 17410 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 1 columns.; line_number: 232 byte_offset_to_start_of_line: 29816 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 1 columns.; line_number: 360 byte_offset_to_start_of_line: 48488 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 1 columns.; line_number: 444 byte_offset_to_start_of_line: 60273 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 1 columns.; line_number: 456 byte_offset_to_start_of_line: 62093 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 1 columns.; line_number: 457 byte_offset_to_start_of_line: 62121 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 1 columns.; line_number: 458 byte_offset_to_start_of_line: 62139 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 1 columns.; line_number: 521 byte_offset_to_start_of_line: 70596 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 1 columns.; line_number: 533 byte_offset_to_start_of_line: 72083 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 1 columns.; line_number: 548 byte_offset_to_start_of_line: 73708 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 1 columns.; line_number: 549 byte_offset_to_start_of_line: 73709 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 1 columns.; line_number: 550 byte_offset_to_start_of_line: 73714 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 1 columns.; line_number: 569 byte_offset_to_start_of_line: 76186 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 1 columns.; line_number: 591 byte_offset_to_start_of_line: 79416 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 1 columns.; line_number: 592 byte_offset_to_start_of_line: 79450 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 1 columns.; line_number: 610 byte_offset_to_start_of_line: 82085 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 1 columns.; line_number: 625 byte_offset_to_start_of_line: 84336 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 1 columns.; line_number: 626 byte_offset_to_start_of_line: 84356 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 1 columns.; line_number: 633 byte_offset_to_start_of_line: 85127 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 1 columns.; line_number: 709 byte_offset_to_start_of_line: 96343 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 1 columns.; line_number: 875 byte_offset_to_start_of_line: 119655 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 2 columns.; line_number: 32 byte_offset_to_start_of_line: 4016 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 2 columns.; line_number: 129 byte_offset_to_start_of_line: 16309 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 2 columns.; line_number: 540 byte_offset_to_start_of_line: 72871 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 2 columns.; line_number: 772 byte_offset_to_start_of_line: 105046 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 2 columns.; line_number: 874 byte_offset_to_start_of_line: 119609 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 3 columns.; line_number: 33 byte_offset_to_start_of_line: 4071 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 3 columns.; line_number: 58 byte_offset_to_start_of_line: 7576 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 3 columns.; line_number: 116 byte_offset_to_start_of_line: 14716 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 3 columns.; line_number: 133 byte_offset_to_start_of_line: 16638 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 3 columns.; line_number: 143 byte_offset_to_start_of_line: 17411 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 3 columns.; line_number: 189 byte_offset_to_start_of_line: 23712 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 3 columns.; line_number: 193 byte_offset_to_start_of_line: 24340 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 3 columns.; line_number: 358 byte_offset_to_start_of_line: 48328 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 3 columns.; line_number: 375 byte_offset_to_start_of_line: 50574 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 3 columns.; line_number: 403 byte_offset_to_start_of_line: 54535 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 3 columns.; line_number: 431 byte_offset_to_start_of_line: 58524 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 3 columns.; line_number: 510 byte_offset_to_start_of_line: 69203 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 3 columns.; line_number: 531 byte_offset_to_start_of_line: 71936 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 3 columns.; line_number: 541 byte_offset_to_start_of_line: 72932 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 3 columns.; line_number: 566 byte_offset_to_start_of_line: 75863 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 3 columns.; line_number: 593 byte_offset_to_start_of_line: 79494 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 3 columns.; line_number: 611 byte_offset_to_start_of_line: 82106 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 3 columns.; line_number: 699 byte_offset_to_start_of_line: 94606 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 3 columns.; line_number: 710 byte_offset_to_start_of_line: 96369 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 4 columns.; line_number: 131 byte_offset_to_start_of_line: 16421 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 4 columns.; line_number: 262 byte_offset_to_start_of_line: 34212 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 4 columns.; line_number: 586 byte_offset_to_start_of_line: 78746 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 4 columns.; line_number: 627 byte_offset_to_start_of_line: 84376 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 4 columns.; line_number: 773 byte_offset_to_start_of_line: 105081 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: You are loading data without specifying data format, data will be treated as CSV format by default. If this is not what you mean, please specify data format by --source_format.

[0m22:53:37.246089 [debug] [Thread-2 (]: Sending event: {'category': 'dbt', 'action': 'run_model', 'label': 'cb5d881a-0b10-41f5-b915-4567115cfa25', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x77c88c2ceed0>]}
[0m22:53:37.253405 [error] [Thread-2 (]: 6 of 9 ERROR loading seed file BronzeLayer.order_reviews ....................... [[31mERROR[0m in 23.46s]
[0m22:53:37.261032 [debug] [Thread-2 (]: Finished running node seed.bigquery_with_dbt.order_reviews
[0m22:53:37.262727 [debug] [Thread-2 (]: Began running node seed.bigquery_with_dbt.sellers
[0m22:53:37.267559 [debug] [Thread-7 (]: Marking all children of 'seed.bigquery_with_dbt.order_reviews' to be skipped because of status 'error'.  Reason: 400 Error while reading data, error message: CSV table encountered too many errors, giving up. Rows: 774; errors: 100. Please look into the errors[] collection for more details.; reason: invalid, message: Error while reading data, error message: CSV table encountered too many errors, giving up. Rows: 774; errors: 100. Please look into the errors[] collection for more details.; reason: invalid, message: Error while reading data, error message: CSV processing encountered too many errors, giving up. Rows: 774; errors: 100; max bad: 0; error percent: 0; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 5 columns.; line_number: 14 byte_offset_to_start_of_line: 1841 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 5 columns.; line_number: 30 byte_offset_to_start_of_line: 3855 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 5 columns.; line_number: 57 byte_offset_to_start_of_line: 7455 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 5 columns.; line_number: 68 byte_offset_to_start_of_line: 8729 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 5 columns.; line_number: 78 byte_offset_to_start_of_line: 10143 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 5 columns.; line_number: 110 byte_offset_to_start_of_line: 14219 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 5 columns.; line_number: 114 byte_offset_to_start_of_line: 14578 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 5 columns.; line_number: 128 byte_offset_to_start_of_line: 16216 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 5 columns.; line_number: 132 byte_offset_to_start_of_line: 16541 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 5 columns.; line_number: 138 byte_offset_to_start_of_line: 17245 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 5 columns.; line_number: 188 byte_offset_to_start_of_line: 23483 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 5 columns.; line_number: 192 byte_offset_to_start_of_line: 24203 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 5 columns.; line_number: 231 byte_offset_to_start_of_line: 29671 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 5 columns.; line_number: 261 byte_offset_to_start_of_line: 34016 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 5 columns.; line_number: 357 byte_offset_to_start_of_line: 48240 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 5 columns.; line_number: 359 byte_offset_to_start_of_line: 48387 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 5 columns.; line_number: 361 byte_offset_to_start_of_line: 48489 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 5 columns.; line_number: 374 byte_offset_to_start_of_line: 50339 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 5 columns.; line_number: 402 byte_offset_to_start_of_line: 54422 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 5 columns.; line_number: 430 byte_offset_to_start_of_line: 58426 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 5 columns.; line_number: 443 byte_offset_to_start_of_line: 60133 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 5 columns.; line_number: 455 byte_offset_to_start_of_line: 61986 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 5 columns.; line_number: 509 byte_offset_to_start_of_line: 69078 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 5 columns.; line_number: 520 byte_offset_to_start_of_line: 70482 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 5 columns.; line_number: 530 byte_offset_to_start_of_line: 71726 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 5 columns.; line_number: 532 byte_offset_to_start_of_line: 71993 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 5 columns.; line_number: 539 byte_offset_to_start_of_line: 72763 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 5 columns.; line_number: 547 byte_offset_to_start_of_line: 73595 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 5 columns.; line_number: 565 byte_offset_to_start_of_line: 75754 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 5 columns.; line_number: 568 byte_offset_to_start_of_line: 76042 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 5 columns.; line_number: 585 byte_offset_to_start_of_line: 78624 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 5 columns.; line_number: 590 byte_offset_to_start_of_line: 79305 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 5 columns.; line_number: 609 byte_offset_to_start_of_line: 81959 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 5 columns.; line_number: 624 byte_offset_to_start_of_line: 84231 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 5 columns.; line_number: 632 byte_offset_to_start_of_line: 84982 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 5 columns.; line_number: 698 byte_offset_to_start_of_line: 94475 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 5 columns.; line_number: 708 byte_offset_to_start_of_line: 96207 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 5 columns.; line_number: 771 byte_offset_to_start_of_line: 104882 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 5 columns.; line_number: 873 byte_offset_to_start_of_line: 119520 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 1 columns.; line_number: 15 byte_offset_to_start_of_line: 1960 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 1 columns.; line_number: 31 byte_offset_to_start_of_line: 3965 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 1 columns.; line_number: 69 byte_offset_to_start_of_line: 8875 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 1 columns.; line_number: 70 byte_offset_to_start_of_line: 8894 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 1 columns.; line_number: 79 byte_offset_to_start_of_line: 10286 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 1 columns.; line_number: 111 byte_offset_to_start_of_line: 14305 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 1 columns.; line_number: 115 byte_offset_to_start_of_line: 14715 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 1 columns.; line_number: 130 byte_offset_to_start_of_line: 16391 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 1 columns.; line_number: 139 byte_offset_to_start_of_line: 17388 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 1 columns.; line_number: 140 byte_offset_to_start_of_line: 17402 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 1 columns.; line_number: 141 byte_offset_to_start_of_line: 17403 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 1 columns.; line_number: 142 byte_offset_to_start_of_line: 17410 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 1 columns.; line_number: 232 byte_offset_to_start_of_line: 29816 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 1 columns.; line_number: 360 byte_offset_to_start_of_line: 48488 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 1 columns.; line_number: 444 byte_offset_to_start_of_line: 60273 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 1 columns.; line_number: 456 byte_offset_to_start_of_line: 62093 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 1 columns.; line_number: 457 byte_offset_to_start_of_line: 62121 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 1 columns.; line_number: 458 byte_offset_to_start_of_line: 62139 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 1 columns.; line_number: 521 byte_offset_to_start_of_line: 70596 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 1 columns.; line_number: 533 byte_offset_to_start_of_line: 72083 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 1 columns.; line_number: 548 byte_offset_to_start_of_line: 73708 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 1 columns.; line_number: 549 byte_offset_to_start_of_line: 73709 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 1 columns.; line_number: 550 byte_offset_to_start_of_line: 73714 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 1 columns.; line_number: 569 byte_offset_to_start_of_line: 76186 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 1 columns.; line_number: 591 byte_offset_to_start_of_line: 79416 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 1 columns.; line_number: 592 byte_offset_to_start_of_line: 79450 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 1 columns.; line_number: 610 byte_offset_to_start_of_line: 82085 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 1 columns.; line_number: 625 byte_offset_to_start_of_line: 84336 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 1 columns.; line_number: 626 byte_offset_to_start_of_line: 84356 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 1 columns.; line_number: 633 byte_offset_to_start_of_line: 85127 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 1 columns.; line_number: 709 byte_offset_to_start_of_line: 96343 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 1 columns.; line_number: 875 byte_offset_to_start_of_line: 119655 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 2 columns.; line_number: 32 byte_offset_to_start_of_line: 4016 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 2 columns.; line_number: 129 byte_offset_to_start_of_line: 16309 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 2 columns.; line_number: 540 byte_offset_to_start_of_line: 72871 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 2 columns.; line_number: 772 byte_offset_to_start_of_line: 105046 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 2 columns.; line_number: 874 byte_offset_to_start_of_line: 119609 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 3 columns.; line_number: 33 byte_offset_to_start_of_line: 4071 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 3 columns.; line_number: 58 byte_offset_to_start_of_line: 7576 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 3 columns.; line_number: 116 byte_offset_to_start_of_line: 14716 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 3 columns.; line_number: 133 byte_offset_to_start_of_line: 16638 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 3 columns.; line_number: 143 byte_offset_to_start_of_line: 17411 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 3 columns.; line_number: 189 byte_offset_to_start_of_line: 23712 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 3 columns.; line_number: 193 byte_offset_to_start_of_line: 24340 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 3 columns.; line_number: 358 byte_offset_to_start_of_line: 48328 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 3 columns.; line_number: 375 byte_offset_to_start_of_line: 50574 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 3 columns.; line_number: 403 byte_offset_to_start_of_line: 54535 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 3 columns.; line_number: 431 byte_offset_to_start_of_line: 58524 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 3 columns.; line_number: 510 byte_offset_to_start_of_line: 69203 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 3 columns.; line_number: 531 byte_offset_to_start_of_line: 71936 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 3 columns.; line_number: 541 byte_offset_to_start_of_line: 72932 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 3 columns.; line_number: 566 byte_offset_to_start_of_line: 75863 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 3 columns.; line_number: 593 byte_offset_to_start_of_line: 79494 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 3 columns.; line_number: 611 byte_offset_to_start_of_line: 82106 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 3 columns.; line_number: 699 byte_offset_to_start_of_line: 94606 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 3 columns.; line_number: 710 byte_offset_to_start_of_line: 96369 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 4 columns.; line_number: 131 byte_offset_to_start_of_line: 16421 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 4 columns.; line_number: 262 byte_offset_to_start_of_line: 34212 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 4 columns.; line_number: 586 byte_offset_to_start_of_line: 78746 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 4 columns.; line_number: 627 byte_offset_to_start_of_line: 84376 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 4 columns.; line_number: 773 byte_offset_to_start_of_line: 105081 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: You are loading data without specifying data format, data will be treated as CSV format by default. If this is not what you mean, please specify data format by --source_format..
[0m22:53:37.272419 [info ] [Thread-2 (]: 9 of 9 START seed file BronzeLayer.sellers ..................................... [RUN]
[0m22:53:37.280010 [debug] [Thread-2 (]: Re-using an available connection from the pool (formerly seed.bigquery_with_dbt.order_reviews, now seed.bigquery_with_dbt.sellers)
[0m22:53:37.280883 [debug] [Thread-2 (]: Began compiling node seed.bigquery_with_dbt.sellers
[0m22:53:37.281593 [debug] [Thread-2 (]: Began executing node seed.bigquery_with_dbt.sellers
[0m22:53:37.311069 [debug] [Thread-2 (]: Opening a new connection, currently in state closed
[0m22:53:40.350052 [debug] [Thread-1 (]: On seed.bigquery_with_dbt.products: /* {"app": "dbt", "dbt_version": "1.9.3", "profile_name": "bigquery_with_dbt", "target_name": "dev", "node_id": "seed.bigquery_with_dbt.products"} */

    alter table `gg-bigquery-datawarehouse`.`BronzeLayer`.`products` set OPTIONS()
  
[0m22:53:41.018899 [debug] [Thread-1 (]: BigQuery adapter: https://console.cloud.google.com/bigquery?project=gg-bigquery-datawarehouse&j=bq:US:47302cdc-3949-4078-96aa-9ade254bc3dd&page=queryresults
[0m22:53:41.980462 [debug] [Thread-1 (]: Writing runtime SQL for node "seed.bigquery_with_dbt.products"
[0m22:53:41.984997 [debug] [Thread-1 (]: Sending event: {'category': 'dbt', 'action': 'run_model', 'label': 'cb5d881a-0b10-41f5-b915-4567115cfa25', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x77c8695f9f50>]}
[0m22:53:41.985769 [info ] [Thread-1 (]: 8 of 9 OK loaded seed file BronzeLayer.products ................................ [[32mINSERT 32951[0m in 19.50s]
[0m22:53:41.986446 [debug] [Thread-1 (]: Finished running node seed.bigquery_with_dbt.products
[0m22:53:49.295540 [debug] [Thread-2 (]: On seed.bigquery_with_dbt.sellers: /* {"app": "dbt", "dbt_version": "1.9.3", "profile_name": "bigquery_with_dbt", "target_name": "dev", "node_id": "seed.bigquery_with_dbt.sellers"} */

    alter table `gg-bigquery-datawarehouse`.`BronzeLayer`.`sellers` set OPTIONS()
  
[0m22:53:50.330471 [debug] [Thread-2 (]: BigQuery adapter: https://console.cloud.google.com/bigquery?project=gg-bigquery-datawarehouse&j=bq:US:0d1be3d6-1be9-4f3b-a0cb-96d65599a824&page=queryresults
[0m22:53:51.587734 [debug] [Thread-2 (]: Writing runtime SQL for node "seed.bigquery_with_dbt.sellers"
[0m22:53:51.590769 [debug] [Thread-2 (]: Sending event: {'category': 'dbt', 'action': 'run_model', 'label': 'cb5d881a-0b10-41f5-b915-4567115cfa25', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x77c88c02b650>]}
[0m22:53:51.591451 [info ] [Thread-2 (]: 9 of 9 OK loaded seed file BronzeLayer.sellers ................................. [[32mINSERT 3095[0m in 14.31s]
[0m22:53:51.592095 [debug] [Thread-2 (]: Finished running node seed.bigquery_with_dbt.sellers
[0m22:54:00.687922 [debug] [Thread-4 (]: On seed.bigquery_with_dbt.orders: /* {"app": "dbt", "dbt_version": "1.9.3", "profile_name": "bigquery_with_dbt", "target_name": "dev", "node_id": "seed.bigquery_with_dbt.orders"} */

    alter table `gg-bigquery-datawarehouse`.`BronzeLayer`.`orders` set OPTIONS()
  
[0m22:54:01.166922 [debug] [Thread-4 (]: BigQuery adapter: https://console.cloud.google.com/bigquery?project=gg-bigquery-datawarehouse&j=bq:US:22de8685-c8ec-477f-befd-e83035e6b848&page=queryresults
[0m22:54:01.820490 [debug] [Thread-4 (]: Writing runtime SQL for node "seed.bigquery_with_dbt.orders"
[0m22:54:01.833336 [debug] [Thread-4 (]: Sending event: {'category': 'dbt', 'action': 'run_model', 'label': 'cb5d881a-0b10-41f5-b915-4567115cfa25', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x77c868ec2a10>]}
[0m22:54:01.836331 [info ] [Thread-4 (]: 7 of 9 OK loaded seed file BronzeLayer.orders .................................. [[32mINSERT 99441[0m in 40.12s]
[0m22:54:01.839556 [debug] [Thread-4 (]: Finished running node seed.bigquery_with_dbt.orders
[0m22:54:12.072051 [debug] [Thread-3 (]: On seed.bigquery_with_dbt.geolocation: /* {"app": "dbt", "dbt_version": "1.9.3", "profile_name": "bigquery_with_dbt", "target_name": "dev", "node_id": "seed.bigquery_with_dbt.geolocation"} */

    alter table `gg-bigquery-datawarehouse`.`BronzeLayer`.`geolocation` set OPTIONS()
  
[0m22:54:12.495714 [debug] [Thread-3 (]: BigQuery adapter: https://console.cloud.google.com/bigquery?project=gg-bigquery-datawarehouse&j=bq:US:0fe5228d-8f2e-4d95-8fc7-3a6e8420c9ce&page=queryresults
[0m22:54:13.086976 [debug] [Thread-3 (]: Writing runtime SQL for node "seed.bigquery_with_dbt.geolocation"
[0m22:54:13.100627 [debug] [Thread-3 (]: Sending event: {'category': 'dbt', 'action': 'run_model', 'label': 'cb5d881a-0b10-41f5-b915-4567115cfa25', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x77c868eee750>]}
[0m22:54:13.103566 [info ] [Thread-3 (]: 3 of 9 OK loaded seed file BronzeLayer.geolocation ............................. [[32mINSERT 1000163[0m in 79.63s]
[0m22:54:13.106725 [debug] [Thread-3 (]: Finished running node seed.bigquery_with_dbt.geolocation
[0m22:54:13.112530 [debug] [MainThread]: Opening a new connection, currently in state closed
[0m22:54:13.117017 [debug] [MainThread]: Connection 'master' was properly closed.
[0m22:54:13.117529 [debug] [MainThread]: Connection 'seed.bigquery_with_dbt.products' was properly closed.
[0m22:54:13.118052 [debug] [MainThread]: Connection 'seed.bigquery_with_dbt.sellers' was properly closed.
[0m22:54:13.118426 [debug] [MainThread]: Connection 'seed.bigquery_with_dbt.geolocation' was properly closed.
[0m22:54:13.118868 [debug] [MainThread]: Connection 'seed.bigquery_with_dbt.orders' was properly closed.
[0m22:54:13.119305 [info ] [MainThread]: 
[0m22:54:13.119736 [info ] [MainThread]: Finished running 9 seeds in 0 hours 1 minutes and 21.15 seconds (81.15s).
[0m22:54:13.122712 [debug] [MainThread]: Command end result
[0m22:54:13.147500 [debug] [MainThread]: Wrote artifact WritableManifest to /mnt/shares/dae-test-projects/DE-DBT-Google-Bigquery/target/manifest.json
[0m22:54:13.149143 [debug] [MainThread]: Wrote artifact SemanticManifest to /mnt/shares/dae-test-projects/DE-DBT-Google-Bigquery/target/semantic_manifest.json
[0m22:54:13.154784 [debug] [MainThread]: Wrote artifact RunExecutionResult to /mnt/shares/dae-test-projects/DE-DBT-Google-Bigquery/target/run_results.json
[0m22:54:13.155291 [info ] [MainThread]: 
[0m22:54:13.155765 [info ] [MainThread]: [31mCompleted with 1 error, 0 partial successes, and 0 warnings:[0m
[0m22:54:13.156204 [info ] [MainThread]: 
[0m22:54:13.157671 [error] [MainThread]:   400 Error while reading data, error message: CSV table encountered too many errors, giving up. Rows: 774; errors: 100. Please look into the errors[] collection for more details.; reason: invalid, message: Error while reading data, error message: CSV table encountered too many errors, giving up. Rows: 774; errors: 100. Please look into the errors[] collection for more details.; reason: invalid, message: Error while reading data, error message: CSV processing encountered too many errors, giving up. Rows: 774; errors: 100; max bad: 0; error percent: 0; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 5 columns.; line_number: 14 byte_offset_to_start_of_line: 1841 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 5 columns.; line_number: 30 byte_offset_to_start_of_line: 3855 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 5 columns.; line_number: 57 byte_offset_to_start_of_line: 7455 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 5 columns.; line_number: 68 byte_offset_to_start_of_line: 8729 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 5 columns.; line_number: 78 byte_offset_to_start_of_line: 10143 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 5 columns.; line_number: 110 byte_offset_to_start_of_line: 14219 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 5 columns.; line_number: 114 byte_offset_to_start_of_line: 14578 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 5 columns.; line_number: 128 byte_offset_to_start_of_line: 16216 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 5 columns.; line_number: 132 byte_offset_to_start_of_line: 16541 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 5 columns.; line_number: 138 byte_offset_to_start_of_line: 17245 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 5 columns.; line_number: 188 byte_offset_to_start_of_line: 23483 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 5 columns.; line_number: 192 byte_offset_to_start_of_line: 24203 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 5 columns.; line_number: 231 byte_offset_to_start_of_line: 29671 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 5 columns.; line_number: 261 byte_offset_to_start_of_line: 34016 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 5 columns.; line_number: 357 byte_offset_to_start_of_line: 48240 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 5 columns.; line_number: 359 byte_offset_to_start_of_line: 48387 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 5 columns.; line_number: 361 byte_offset_to_start_of_line: 48489 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 5 columns.; line_number: 374 byte_offset_to_start_of_line: 50339 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 5 columns.; line_number: 402 byte_offset_to_start_of_line: 54422 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 5 columns.; line_number: 430 byte_offset_to_start_of_line: 58426 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 5 columns.; line_number: 443 byte_offset_to_start_of_line: 60133 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 5 columns.; line_number: 455 byte_offset_to_start_of_line: 61986 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 5 columns.; line_number: 509 byte_offset_to_start_of_line: 69078 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 5 columns.; line_number: 520 byte_offset_to_start_of_line: 70482 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 5 columns.; line_number: 530 byte_offset_to_start_of_line: 71726 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 5 columns.; line_number: 532 byte_offset_to_start_of_line: 71993 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 5 columns.; line_number: 539 byte_offset_to_start_of_line: 72763 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 5 columns.; line_number: 547 byte_offset_to_start_of_line: 73595 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 5 columns.; line_number: 565 byte_offset_to_start_of_line: 75754 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 5 columns.; line_number: 568 byte_offset_to_start_of_line: 76042 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 5 columns.; line_number: 585 byte_offset_to_start_of_line: 78624 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 5 columns.; line_number: 590 byte_offset_to_start_of_line: 79305 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 5 columns.; line_number: 609 byte_offset_to_start_of_line: 81959 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 5 columns.; line_number: 624 byte_offset_to_start_of_line: 84231 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 5 columns.; line_number: 632 byte_offset_to_start_of_line: 84982 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 5 columns.; line_number: 698 byte_offset_to_start_of_line: 94475 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 5 columns.; line_number: 708 byte_offset_to_start_of_line: 96207 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 5 columns.; line_number: 771 byte_offset_to_start_of_line: 104882 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 5 columns.; line_number: 873 byte_offset_to_start_of_line: 119520 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 1 columns.; line_number: 15 byte_offset_to_start_of_line: 1960 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 1 columns.; line_number: 31 byte_offset_to_start_of_line: 3965 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 1 columns.; line_number: 69 byte_offset_to_start_of_line: 8875 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 1 columns.; line_number: 70 byte_offset_to_start_of_line: 8894 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 1 columns.; line_number: 79 byte_offset_to_start_of_line: 10286 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 1 columns.; line_number: 111 byte_offset_to_start_of_line: 14305 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 1 columns.; line_number: 115 byte_offset_to_start_of_line: 14715 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 1 columns.; line_number: 130 byte_offset_to_start_of_line: 16391 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 1 columns.; line_number: 139 byte_offset_to_start_of_line: 17388 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 1 columns.; line_number: 140 byte_offset_to_start_of_line: 17402 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 1 columns.; line_number: 141 byte_offset_to_start_of_line: 17403 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 1 columns.; line_number: 142 byte_offset_to_start_of_line: 17410 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 1 columns.; line_number: 232 byte_offset_to_start_of_line: 29816 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 1 columns.; line_number: 360 byte_offset_to_start_of_line: 48488 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 1 columns.; line_number: 444 byte_offset_to_start_of_line: 60273 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 1 columns.; line_number: 456 byte_offset_to_start_of_line: 62093 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 1 columns.; line_number: 457 byte_offset_to_start_of_line: 62121 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 1 columns.; line_number: 458 byte_offset_to_start_of_line: 62139 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 1 columns.; line_number: 521 byte_offset_to_start_of_line: 70596 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 1 columns.; line_number: 533 byte_offset_to_start_of_line: 72083 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 1 columns.; line_number: 548 byte_offset_to_start_of_line: 73708 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 1 columns.; line_number: 549 byte_offset_to_start_of_line: 73709 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 1 columns.; line_number: 550 byte_offset_to_start_of_line: 73714 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 1 columns.; line_number: 569 byte_offset_to_start_of_line: 76186 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 1 columns.; line_number: 591 byte_offset_to_start_of_line: 79416 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 1 columns.; line_number: 592 byte_offset_to_start_of_line: 79450 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 1 columns.; line_number: 610 byte_offset_to_start_of_line: 82085 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 1 columns.; line_number: 625 byte_offset_to_start_of_line: 84336 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 1 columns.; line_number: 626 byte_offset_to_start_of_line: 84356 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 1 columns.; line_number: 633 byte_offset_to_start_of_line: 85127 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 1 columns.; line_number: 709 byte_offset_to_start_of_line: 96343 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 1 columns.; line_number: 875 byte_offset_to_start_of_line: 119655 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 2 columns.; line_number: 32 byte_offset_to_start_of_line: 4016 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 2 columns.; line_number: 129 byte_offset_to_start_of_line: 16309 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 2 columns.; line_number: 540 byte_offset_to_start_of_line: 72871 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 2 columns.; line_number: 772 byte_offset_to_start_of_line: 105046 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 2 columns.; line_number: 874 byte_offset_to_start_of_line: 119609 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 3 columns.; line_number: 33 byte_offset_to_start_of_line: 4071 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 3 columns.; line_number: 58 byte_offset_to_start_of_line: 7576 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 3 columns.; line_number: 116 byte_offset_to_start_of_line: 14716 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 3 columns.; line_number: 133 byte_offset_to_start_of_line: 16638 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 3 columns.; line_number: 143 byte_offset_to_start_of_line: 17411 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 3 columns.; line_number: 189 byte_offset_to_start_of_line: 23712 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 3 columns.; line_number: 193 byte_offset_to_start_of_line: 24340 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 3 columns.; line_number: 358 byte_offset_to_start_of_line: 48328 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 3 columns.; line_number: 375 byte_offset_to_start_of_line: 50574 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 3 columns.; line_number: 403 byte_offset_to_start_of_line: 54535 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 3 columns.; line_number: 431 byte_offset_to_start_of_line: 58524 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 3 columns.; line_number: 510 byte_offset_to_start_of_line: 69203 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 3 columns.; line_number: 531 byte_offset_to_start_of_line: 71936 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 3 columns.; line_number: 541 byte_offset_to_start_of_line: 72932 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 3 columns.; line_number: 566 byte_offset_to_start_of_line: 75863 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 3 columns.; line_number: 593 byte_offset_to_start_of_line: 79494 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 3 columns.; line_number: 611 byte_offset_to_start_of_line: 82106 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 3 columns.; line_number: 699 byte_offset_to_start_of_line: 94606 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 3 columns.; line_number: 710 byte_offset_to_start_of_line: 96369 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 4 columns.; line_number: 131 byte_offset_to_start_of_line: 16421 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 4 columns.; line_number: 262 byte_offset_to_start_of_line: 34212 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 4 columns.; line_number: 586 byte_offset_to_start_of_line: 78746 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 4 columns.; line_number: 627 byte_offset_to_start_of_line: 84376 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: Error while reading data, error message: CSV table references column position 6, but line contains only 4 columns.; line_number: 773 byte_offset_to_start_of_line: 105081 column_index: 6 column_name: "review_answer_tim..." column_type: DATETIME; reason: invalid, message: You are loading data without specifying data format, data will be treated as CSV format by default. If this is not what you mean, please specify data format by --source_format.
[0m22:54:13.160216 [info ] [MainThread]: 
[0m22:54:13.160855 [info ] [MainThread]: Done. PASS=8 WARN=0 ERROR=1 SKIP=0 TOTAL=9
[0m22:54:13.162107 [debug] [MainThread]: Resource report: {"command_name": "seed", "command_success": false, "command_wall_clock_time": 82.731155, "process_in_blocks": "0", "process_kernel_time": 1.572815, "process_mem_max_rss": "1826116", "process_out_blocks": "0", "process_user_time": 41.06007}
[0m22:54:13.162629 [debug] [MainThread]: Command `dbt seed` failed at 22:54:13.162538 after 82.73 seconds
[0m22:54:13.163154 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x77c8b0c3c190>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x77c8b45ba2d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x77c869757510>]}
[0m22:54:13.163581 [debug] [MainThread]: Flushing usage events
[0m22:54:14.646208 [debug] [MainThread]: An error was encountered while trying to flush usage events
